#pragma  once
#include <cstdint>

namespace Z_Engine::Inputs {
	
	typedef enum class KeyCode : std::int32_t {

		A				   = 0x004,
		B				   = 0x005,
		C				   = 0x006,
		D				   = 0x007,
		E				   = 0x008,
		F				   = 0x009,
		G				   = 0x00A,
		H				   = 0x00B,
		I				   = 0x00C,
		J				   = 0x00D,
		K				   = 0x00E,
		L				   = 0x00F,
		M				   = 0x010,
		N				   = 0x011,
		O				   = 0x012,
		P				   = 0x013,
		Q				   = 0x014,
		R				   = 0x015,
		S				   = 0x016,
		T				   = 0x017,
		U				   = 0x018,
		V				   = 0x019,
		W				   = 0x01A,
		X				   = 0x01B,
		Y				   = 0x01C,
		Z				   = 0x01D,
		RETURN			   = 0x028,
		ESCAPE			   = 0x029,
		BACKSPACE		   = 0x02A,
		TAB				   = 0x02B,
		SPACE			   = 0x02C,
		MINUS			   = 0x02D,
		EQUALS			   = 0x02E,
		LEFTBRACKET		   = 0x02F,
		RIGHTBRACKET	   = 0x030,
		BACKSLASH		   = 0x031,
		NONUSHASH		   = 0x032,
		SEMICOLON		   = 0x033,
		APOSTROPHE		   = 0x034,
		GRAVE			   = 0x035,
		COMMA			   = 0x036,
		PERIOD			   = 0x037,
		SLASH			   = 0x038,
		CAPSLOCK		   = 0x039,
		F1				   = 0x03A,
		F2				   = 0x03B,
		F3				   = 0x03C,
		F4				   = 0x03D,
		F5				   = 0x03E,
		F6				   = 0x03F,
		F7				   = 0x040,
		F8				   = 0x041,
		F9				   = 0x042,
		F10				   = 0x043,
		F11				   = 0x044,
		F12				   = 0x045,
		PRINTSCREEN		   = 0x046,
		SCROLLLOCK		   = 0x047,
		PAUSE			   = 0x048,
		INSERT			   = 0x049,
		HOME			   = 0x04A,
		PAGEUP			   = 0x04B,
		DELETE			   = 0x04C,
		END				   = 0x04D,
		PAGEDOWN		   = 0x04E,
		RIGHT			   = 0x04F,
		LEFT			   = 0x050,
		DOWN			   = 0x051,
		UP				   = 0x052,
		NUMLOCKCLEAR	   = 0x053,
		KP_DIVIDE		   = 0x054,
		KP_MULTIPLY		   = 0x055,
		KP_MINUS		   = 0x056,
		KP_PLUS			   = 0x057,
		KP_ENTER		   = 0x058,
		KP_1			   = 0x059,
		KP_2			   = 0x05A,
		KP_3			   = 0x05B,
		KP_4			   = 0x05C,
		KP_5			   = 0x05D,
		KP_6			   = 0x05E,
		KP_7			   = 0x05F,
		KP_8			   = 0x060,
		KP_9			   = 0x061,
		KP_0			   = 0x062,
		KP_PERIOD		   = 0x063,
		NONUSBACKSLASH	   = 0x064,
		APPLICATION		   = 0x065,
		POWER			   = 0x066,
		KP_EQUALS		   = 0x067,
		F13				   = 0x068,
		F14				   = 0x069,
		F15				   = 0x06A,
		F16				   = 0x06B,
		F17				   = 0x06C,
		F18				   = 0x06D,
		F19				   = 0x06E,
		F20				   = 0x06F,
		F21				   = 0x070,
		F22				   = 0x071,
		F23				   = 0x072,
		F24				   = 0x073,
		EXECUTE			   = 0x074,
		HELP			   = 0x075,
		MENU			   = 0x076,
		SELECT			   = 0x077,
		STOP			   = 0x078,
		AGAIN			   = 0x079,
		UNDO			   = 0x07A,
		CUT				   = 0x07B,
		COPY			   = 0x07C,
		PASTE			   = 0x07D,
		FIND			   = 0x07E,
		MUTE			   = 0x07F,
		VOLUMEUP		   = 0x080,
		VOLUMEDOWN		   = 0x081,
		KP_COMMA		   = 0x085,
		KP_EQUALSAS400	   = 0x086,
		INTERNATIONAL1	   = 0x087,
		INTERNATIONAL2	   = 0x088,
		INTERNATIONAL3	   = 0x089,
		INTERNATIONAL4	   = 0x08A,
		INTERNATIONAL5	   = 0x08B,
		INTERNATIONAL6	   = 0x08C,
		INTERNATIONAL7	   = 0x08D,
		INTERNATIONAL8	   = 0x08E,
		INTERNATIONAL9	   = 0x08F,
		LANG1			   = 0x090,
		LANG2			   = 0x091,
		LANG3			   = 0x092,
		LANG4			   = 0x093,
		LANG5			   = 0x094,
		LANG6			   = 0x095,
		LANG7			   = 0x096,
		LANG8			   = 0x097,
		LANG9			   = 0x098,
		ALTERASE		   = 0x099,
		SYSREQ			   = 0x09A,
		CANCEL			   = 0x09B,
		CLEAR			   = 0x09C,
		PRIOR			   = 0x09D,
		RETURN2			   = 0x09E,
		SEPARATOR		   = 0x09F,
		OUT				   = 0x0A0,
		OPER			   = 0x0A1,
		CLEARAGAIN		   = 0x0A2,
		CRSEL			   = 0x0A3,
		EXSEL			   = 0x0A4,
		KP_00			   = 0x0B0,
		KP_000			   = 0x0B1,
		THOUSANDSSEPARATOR = 0x0B2,
		DECIMALSEPARATOR   = 0x0B3,
		CURRENCYUNIT       = 0x0B4,
		CURRENCYSUBUNIT    = 0x0B5,
		KP_LEFTPAREN       = 0x0B6,
		KP_RIGHTPAREN      = 0x0B7,
		KP_LEFTBRACE       = 0x0B8,
		KP_RIGHTBRACE      = 0x0B9,
		KP_TAB             = 0x0BA,
		KP_BACKSPACE       = 0x0BB,
		KP_A			   = 0x0BC,
		KP_B			   = 0x0BD,
		KP_C			   = 0x0BE,
		KP_D			   = 0x0BF,
		KP_E			   = 0x0C0,
		KP_F			   = 0x0C1,
		KP_XOR			   = 0x0C2,
		KP_POWER		   = 0x0C3,
		KP_PERCENT		   = 0x0C4,
		KP_LESS			   = 0x0C5,
		KP_GREATER		   = 0x0C6,
		KP_AMPERSAND       = 0x0C7,
		KP_DBLAMPERSAND    = 0x0C8,
		KP_VERTICALBAR     = 0x0C9,
		KP_DBLVERTICALBAR  = 0x0CA,
		KP_COLON		   = 0x0CB,
		KP_HASH			   = 0x0CC,
		KP_SPACE		   = 0x0CD,
		KP_AT			   = 0x0CE,
		KP_EXCLAM		   = 0x0CF,
		KP_MEMSTORE		   = 0x0D0,
		KP_MEMRECALL	   = 0x0D1,
		KP_MEMCLEAR		   = 0x0D2,
		KP_MEMADD		   = 0x0D3,
		KP_MEMSUBTRACT	   = 0x0D4,
		KP_MEMMULTIPLY	   = 0x0D5,
		KP_MEMDIVIDE	   = 0x0D6,
		KP_PLUSMINUS	   = 0x0D7,
		KP_CLEAR		   = 0x0D8,
		KP_CLEARENTRY	   = 0x0D9,
		KP_BINARY		   = 0x0DA,
		KP_OCTAL		   = 0x0DB,
		KP_DECIMAL		   = 0x0DC,
		KP_HEXADECIMAL	   = 0x0DD,
		LCTRL			   = 0x0E0,
		LSHIFT			   = 0x0E1,
		LALT			   = 0x0E2,
		LGUI			   = 0x0E3,
		RCTRL			   = 0x0E4,
		RSHIFT			   = 0x0E5,
		RALT			   = 0x0E6,
		RGUI			   = 0x0E7,
		MODE			   = 0x101,
		AUDIONEXT		   = 0x102,
		AUDIOPREV		   = 0x103,
		AUDIOSTOP		   = 0x104,
		AUDIOPLAY		   = 0x105,
		AUDIOMUTE		   = 0x106,
		MEDIASELECT		   = 0x107,
		WWW				   = 0x108,
		MAIL			   = 0x109,
		CALCULATOR		   = 0x10A,
		COMPUTER		   = 0x10B,
		AC_SEARCH		   = 0x10C,
		AC_HOME			   = 0x10D,
		AC_BACK			   = 0x10E,
		AC_FORWARD		   = 0x10F,
		AC_STOP			   = 0x110,
		AC_REFRESH		   = 0x111,
		AC_BOOKMARKS	   = 0x112,
		BRIGHTNESSDOWN	   = 0x113,
		BRIGHTNESSUP	   = 0x114,
		DISPLAYSWITCH	   = 0x115,
		KBDILLUMTOGGLE	   = 0x116,
		KBDILLUMDOWN	   = 0x117,
		KBDILLUMUP		   = 0x118,
		EJECT			   = 0x119,
		SLEEP			   = 0x11A,
		APP1			   = 0x11B,
		APP2			   = 0x11C,

		MOUSE_LEFT  = 1,
		MOUSE_WHEEL = 2,
		MOUSE_RIGHT = 3,

	} Key;

}

#define Z_ENGINE_KEY_A							Z_Engine::Inputs::Key::A
#define Z_ENGINE_KEY_B							Z_Engine::Inputs::Key::B
#define Z_ENGINE_KEY_C							Z_Engine::Inputs::Key::C
#define Z_ENGINE_KEY_D							Z_Engine::Inputs::Key::D
#define Z_ENGINE_KEY_E							Z_Engine::Inputs::Key::E
#define Z_ENGINE_KEY_F							Z_Engine::Inputs::Key::F
#define Z_ENGINE_KEY_G							Z_Engine::Inputs::Key::G
#define Z_ENGINE_KEY_H							Z_Engine::Inputs::Key::H
#define Z_ENGINE_KEY_I							Z_Engine::Inputs::Key::I
#define Z_ENGINE_KEY_J							Z_Engine::Inputs::Key::J
#define Z_ENGINE_KEY_K							Z_Engine::Inputs::Key::K
#define Z_ENGINE_KEY_L							Z_Engine::Inputs::Key::L
#define Z_ENGINE_KEY_M							Z_Engine::Inputs::Key::M
#define Z_ENGINE_KEY_N							Z_Engine::Inputs::Key::N
#define Z_ENGINE_KEY_O							Z_Engine::Inputs::Key::O
#define Z_ENGINE_KEY_P							Z_Engine::Inputs::Key::P
#define Z_ENGINE_KEY_Q							Z_Engine::Inputs::Key::Q
#define Z_ENGINE_KEY_R							Z_Engine::Inputs::Key::R
#define Z_ENGINE_KEY_S							Z_Engine::Inputs::Key::S
#define Z_ENGINE_KEY_T							Z_Engine::Inputs::Key::T
#define Z_ENGINE_KEY_U							Z_Engine::Inputs::Key::U
#define Z_ENGINE_KEY_V							Z_Engine::Inputs::Key::V
#define Z_ENGINE_KEY_W							Z_Engine::Inputs::Key::W
#define Z_ENGINE_KEY_X							Z_Engine::Inputs::Key::X
#define Z_ENGINE_KEY_Y							Z_Engine::Inputs::Key::Y
#define Z_ENGINE_KEY_Z							Z_Engine::Inputs::Key::Z
#define Z_ENGINE_KEY_RETURN						Z_Engine::Inputs::Key::RETURN
#define Z_ENGINE_KEY_ESCAPE						Z_Engine::Inputs::Key::ESCAPE
#define Z_ENGINE_KEY_BACKSPACE					Z_Engine::Inputs::Key::BACKSPACE
#define Z_ENGINE_KEY_TAB						Z_Engine::Inputs::Key::TAB
#define Z_ENGINE_KEY_SPACE						Z_Engine::Inputs::Key::SPACE
#define Z_ENGINE_KEY_MINUS						Z_Engine::Inputs::Key::MINUS
#define Z_ENGINE_KEY_EQUALS						Z_Engine::Inputs::Key::EQUALS
#define Z_ENGINE_KEY_LEFTBRACKET				Z_Engine::Inputs::Key::LEFTBRACKET
#define Z_ENGINE_KEY_RIGHTBRACKET				Z_Engine::Inputs::Key::RIGHTBRACKET
#define Z_ENGINE_KEY_BACKSLASH					Z_Engine::Inputs::Key::BACKSLASH
#define Z_ENGINE_KEY_NONUSHASH					Z_Engine::Inputs::Key::NONUSHASH
#define Z_ENGINE_KEY_SEMICOLON					Z_Engine::Inputs::Key::SEMICOLON
#define Z_ENGINE_KEY_APOSTROPHE					Z_Engine::Inputs::Key::APOSTROPHE
#define Z_ENGINE_KEY_GRAVE						Z_Engine::Inputs::Key::GRAVE
#define Z_ENGINE_KEY_COMMA						Z_Engine::Inputs::Key::COMMA
#define Z_ENGINE_KEY_PERIOD						Z_Engine::Inputs::Key::PERIOD
#define Z_ENGINE_KEY_SLASH						Z_Engine::Inputs::Key::SLASH
#define Z_ENGINE_KEY_CAPSLOCK					Z_Engine::Inputs::Key::CAPSLOCK
#define Z_ENGINE_KEY_F1							Z_Engine::Inputs::Key::F1
#define Z_ENGINE_KEY_F2							Z_Engine::Inputs::Key::F2
#define Z_ENGINE_KEY_F3							Z_Engine::Inputs::Key::F3
#define Z_ENGINE_KEY_F4							Z_Engine::Inputs::Key::F4
#define Z_ENGINE_KEY_F5							Z_Engine::Inputs::Key::F5
#define Z_ENGINE_KEY_F6							Z_Engine::Inputs::Key::F6
#define Z_ENGINE_KEY_F7							Z_Engine::Inputs::Key::F7
#define Z_ENGINE_KEY_F8							Z_Engine::Inputs::Key::F8
#define Z_ENGINE_KEY_F9							Z_Engine::Inputs::Key::F9
#define Z_ENGINE_KEY_F10						Z_Engine::Inputs::Key::F10
#define Z_ENGINE_KEY_F11						Z_Engine::Inputs::Key::F11
#define Z_ENGINE_KEY_F12						Z_Engine::Inputs::Key::F12
#define Z_ENGINE_KEY_PRINTSCREEN				Z_Engine::Inputs::Key::PRINTSCREEN
#define Z_ENGINE_KEY_SCROLLLOCK					Z_Engine::Inputs::Key::SCROLLLOCK
#define Z_ENGINE_KEY_PAUSE						Z_Engine::Inputs::Key::PAUSE
#define Z_ENGINE_KEY_INSERT						Z_Engine::Inputs::Key::INSERT
#define Z_ENGINE_KEY_HOME						Z_Engine::Inputs::Key::HOME
#define Z_ENGINE_KEY_PAGEUP						Z_Engine::Inputs::Key::PAGEUP
#define Z_ENGINE_KEY_DELETE						Z_Engine::Inputs::Key::DELETE
#define Z_ENGINE_KEY_END						Z_Engine::Inputs::Key::END
#define Z_ENGINE_KEY_PAGEDOWN					Z_Engine::Inputs::Key::PAGEDOWN
#define Z_ENGINE_KEY_RIGHT						Z_Engine::Inputs::Key::RIGHT
#define Z_ENGINE_KEY_LEFT						Z_Engine::Inputs::Key::LEFT
#define Z_ENGINE_KEY_DOWN						Z_Engine::Inputs::Key::DOWN
#define Z_ENGINE_KEY_UP							Z_Engine::Inputs::Key::UP
#define Z_ENGINE_KEY_NUMLOCKCLEAR				Z_Engine::Inputs::Key::NUMLOCKCLEAR
#define Z_ENGINE_KEY_KP_DIVIDE					Z_Engine::Inputs::Key::KP_DIVIDE
#define Z_ENGINE_KEY_KP_MULTIPLY				Z_Engine::Inputs::Key::KP_MULTIPLY
#define Z_ENGINE_KEY_KP_MINUS					Z_Engine::Inputs::Key::KP_MINUS
#define Z_ENGINE_KEY_KP_PLUS					Z_Engine::Inputs::Key::KP_PLUS
#define Z_ENGINE_KEY_KP_ENTER					Z_Engine::Inputs::Key::KP_ENTER
#define Z_ENGINE_KEY_KP_1						Z_Engine::Inputs::Key::KP_1
#define Z_ENGINE_KEY_KP_2						Z_Engine::Inputs::Key::KP_2
#define Z_ENGINE_KEY_KP_3						Z_Engine::Inputs::Key::KP_3
#define Z_ENGINE_KEY_KP_4						Z_Engine::Inputs::Key::KP_4
#define Z_ENGINE_KEY_KP_5						Z_Engine::Inputs::Key::KP_5
#define Z_ENGINE_KEY_KP_6						Z_Engine::Inputs::Key::KP_6
#define Z_ENGINE_KEY_KP_7						Z_Engine::Inputs::Key::KP_7
#define Z_ENGINE_KEY_KP_8						Z_Engine::Inputs::Key::KP_8
#define Z_ENGINE_KEY_KP_9						Z_Engine::Inputs::Key::KP_9
#define Z_ENGINE_KEY_KP_0						Z_Engine::Inputs::Key::KP_0
#define Z_ENGINE_KEY_KP_PERIOD					Z_Engine::Inputs::Key::KP_PERIOD
#define Z_ENGINE_KEY_NONUSBACKSLASH				Z_Engine::Inputs::Key::NONUSBACKSLASH
#define Z_ENGINE_KEY_APPLICATION				Z_Engine::Inputs::Key::APPLICATION
#define Z_ENGINE_KEY_POWER						Z_Engine::Inputs::Key::POWER
#define Z_ENGINE_KEY_KP_EQUALS					Z_Engine::Inputs::Key::KP_EQUALS
#define Z_ENGINE_KEY_F13						Z_Engine::Inputs::Key::F13
#define Z_ENGINE_KEY_F14						Z_Engine::Inputs::Key::F14
#define Z_ENGINE_KEY_F15						Z_Engine::Inputs::Key::F15
#define Z_ENGINE_KEY_F16						Z_Engine::Inputs::Key::F16
#define Z_ENGINE_KEY_F17						Z_Engine::Inputs::Key::F17
#define Z_ENGINE_KEY_F18						Z_Engine::Inputs::Key::F18
#define Z_ENGINE_KEY_F19						Z_Engine::Inputs::Key::F19
#define Z_ENGINE_KEY_F20						Z_Engine::Inputs::Key::F20
#define Z_ENGINE_KEY_F21						Z_Engine::Inputs::Key::F21
#define Z_ENGINE_KEY_F22						Z_Engine::Inputs::Key::F22
#define Z_ENGINE_KEY_F23						Z_Engine::Inputs::Key::F23
#define Z_ENGINE_KEY_F24						Z_Engine::Inputs::Key::F24
#define Z_ENGINE_KEY_EXECUTE					Z_Engine::Inputs::Key::EXECUTE
#define Z_ENGINE_KEY_HELP						Z_Engine::Inputs::Key::HELP
#define Z_ENGINE_KEY_MENU						Z_Engine::Inputs::Key::MENU
#define Z_ENGINE_KEY_SELECT						Z_Engine::Inputs::Key::SELECT
#define Z_ENGINE_KEY_STOP						Z_Engine::Inputs::Key::STOP
#define Z_ENGINE_KEY_AGAIN						Z_Engine::Inputs::Key::AGAIN
#define Z_ENGINE_KEY_UNDO						Z_Engine::Inputs::Key::UNDO
#define Z_ENGINE_KEY_CUT						Z_Engine::Inputs::Key::CUT
#define Z_ENGINE_KEY_COPY						Z_Engine::Inputs::Key::COPY
#define Z_ENGINE_KEY_PASTE						Z_Engine::Inputs::Key::PASTE
#define Z_ENGINE_KEY_FIND						Z_Engine::Inputs::Key::FIND
#define Z_ENGINE_KEY_MUTE						Z_Engine::Inputs::Key::MUTE
#define Z_ENGINE_KEY_VOLUMEUP					Z_Engine::Inputs::Key::VOLUMEUP
#define Z_ENGINE_KEY_VOLUMEDOWN					Z_Engine::Inputs::Key::VOLUMEDOWN
#define Z_ENGINE_KEY_KP_COMMA					Z_Engine::Inputs::Key::KP_COMMA
#define Z_ENGINE_KEY_KP_EQUALSAS400				Z_Engine::Inputs::Key::KP_EQUALSAS400
#define Z_ENGINE_KEY_INTERNATIONAL1				Z_Engine::Inputs::Key::INTERNATIONAL1
#define Z_ENGINE_KEY_INTERNATIONAL2				Z_Engine::Inputs::Key::INTERNATIONAL2
#define Z_ENGINE_KEY_INTERNATIONAL3				Z_Engine::Inputs::Key::INTERNATIONAL3
#define Z_ENGINE_KEY_INTERNATIONAL4				Z_Engine::Inputs::Key::INTERNATIONAL4
#define Z_ENGINE_KEY_INTERNATIONAL5				Z_Engine::Inputs::Key::INTERNATIONAL5
#define Z_ENGINE_KEY_INTERNATIONAL6				Z_Engine::Inputs::Key::INTERNATIONAL6
#define Z_ENGINE_KEY_INTERNATIONAL7				Z_Engine::Inputs::Key::INTERNATIONAL7
#define Z_ENGINE_KEY_INTERNATIONAL8				Z_Engine::Inputs::Key::INTERNATIONAL8
#define Z_ENGINE_KEY_INTERNATIONAL9				Z_Engine::Inputs::Key::INTERNATIONAL9
#define Z_ENGINE_KEY_LANG1						Z_Engine::Inputs::Key::LANG1
#define Z_ENGINE_KEY_LANG2						Z_Engine::Inputs::Key::LANG2
#define Z_ENGINE_KEY_LANG3						Z_Engine::Inputs::Key::LANG3
#define Z_ENGINE_KEY_LANG4						Z_Engine::Inputs::Key::LANG4
#define Z_ENGINE_KEY_LANG5						Z_Engine::Inputs::Key::LANG5
#define Z_ENGINE_KEY_LANG6						Z_Engine::Inputs::Key::LANG6
#define Z_ENGINE_KEY_LANG7						Z_Engine::Inputs::Key::LANG7
#define Z_ENGINE_KEY_LANG8						Z_Engine::Inputs::Key::LANG8
#define Z_ENGINE_KEY_LANG9						Z_Engine::Inputs::Key::LANG9
#define Z_ENGINE_KEY_ALTERASE					Z_Engine::Inputs::Key::ALTERASE
#define Z_ENGINE_KEY_SYSREQ						Z_Engine::Inputs::Key::SYSREQ
#define Z_ENGINE_KEY_CANCEL						Z_Engine::Inputs::Key::CANCEL
#define Z_ENGINE_KEY_CLEAR						Z_Engine::Inputs::Key::CLEAR
#define Z_ENGINE_KEY_PRIOR						Z_Engine::Inputs::Key::PRIOR
#define Z_ENGINE_KEY_RETURN2					Z_Engine::Inputs::Key::RETURN2
#define Z_ENGINE_KEY_SEPARATOR					Z_Engine::Inputs::Key::SEPARATOR
#define Z_ENGINE_KEY_OUT						Z_Engine::Inputs::Key::OUT
#define Z_ENGINE_KEY_OPER						Z_Engine::Inputs::Key::OPER
#define Z_ENGINE_KEY_CLEARAGAIN					Z_Engine::Inputs::Key::CLEARAGAIN
#define Z_ENGINE_KEY_CRSEL						Z_Engine::Inputs::Key::CRSEL
#define Z_ENGINE_KEY_EXSEL						Z_Engine::Inputs::Key::EXSEL
#define Z_ENGINE_KEY_KP_00						Z_Engine::Inputs::Key::KP_00
#define Z_ENGINE_KEY_KP_000						Z_Engine::Inputs::Key::KP_000
#define Z_ENGINE_KEY_THOUSANDSSEPARATOR			Z_Engine::Inputs::Key::THOUSANDSSEPARATOR
#define Z_ENGINE_KEY_DECIMALSEPARATOR			Z_Engine::Inputs::Key::DECIMALSEPARATOR
#define Z_ENGINE_KEY_CURRENCYUNIT				Z_Engine::Inputs::Key::CURRENCYUNIT
#define Z_ENGINE_KEY_CURRENCYSUBUNIT			Z_Engine::Inputs::Key::CURRENCYSUBUNIT
#define Z_ENGINE_KEY_KP_LEFTPAREN				Z_Engine::Inputs::Key::KP_LEFTPAREN
#define Z_ENGINE_KEY_KP_RIGHTPAREN				Z_Engine::Inputs::Key::KP_RIGHTPAREN
#define Z_ENGINE_KEY_KP_LEFTBRACE				Z_Engine::Inputs::Key::KP_LEFTBRACE
#define Z_ENGINE_KEY_KP_RIGHTBRACE				Z_Engine::Inputs::Key::KP_RIGHTBRACE
#define Z_ENGINE_KEY_KP_TAB						Z_Engine::Inputs::Key::KP_TAB
#define Z_ENGINE_KEY_KP_BACKSPACE				Z_Engine::Inputs::Key::KP_BACKSPACE
#define Z_ENGINE_KEY_KP_A						Z_Engine::Inputs::Key::KP_A
#define Z_ENGINE_KEY_KP_B						Z_Engine::Inputs::Key::KP_B
#define Z_ENGINE_KEY_KP_C						Z_Engine::Inputs::Key::KP_C
#define Z_ENGINE_KEY_KP_D						Z_Engine::Inputs::Key::KP_D
#define Z_ENGINE_KEY_KP_E						Z_Engine::Inputs::Key::KP_E
#define Z_ENGINE_KEY_KP_F						Z_Engine::Inputs::Key::KP_F
#define Z_ENGINE_KEY_KP_XOR						Z_Engine::Inputs::Key::KP_XOR
#define Z_ENGINE_KEY_KP_POWER					Z_Engine::Inputs::Key::KP_POWER
#define Z_ENGINE_KEY_KP_PERCENT					Z_Engine::Inputs::Key::KP_PERCENT
#define Z_ENGINE_KEY_KP_LESS					Z_Engine::Inputs::Key::KP_LESS
#define Z_ENGINE_KEY_KP_GREATER					Z_Engine::Inputs::Key::KP_GREATER
#define Z_ENGINE_KEY_KP_AMPERSAND				Z_Engine::Inputs::Key::KP_AMPERSAND
#define Z_ENGINE_KEY_KP_DBLAMPERSAND			Z_Engine::Inputs::Key::KP_DBLAMPERSAND
#define Z_ENGINE_KEY_KP_VERTICALBAR				Z_Engine::Inputs::Key::KP_VERTICALBAR
#define Z_ENGINE_KEY_KP_DBLVERTICALBAR			Z_Engine::Inputs::Key::KP_DBLVERTICALBAR
#define Z_ENGINE_KEY_KP_COLON					Z_Engine::Inputs::Key::KP_COLON
#define Z_ENGINE_KEY_KP_HASH					Z_Engine::Inputs::Key::KP_HASH
#define Z_ENGINE_KEY_KP_SPACE					Z_Engine::Inputs::Key::KP_SPACE
#define Z_ENGINE_KEY_KP_AT						Z_Engine::Inputs::Key::KP_AT
#define Z_ENGINE_KEY_KP_EXCLAM					Z_Engine::Inputs::Key::KP_EXCLAM
#define Z_ENGINE_KEY_KP_MEMSTORE				Z_Engine::Inputs::Key::KP_MEMSTORE
#define Z_ENGINE_KEY_KP_MEMRECALL				Z_Engine::Inputs::Key::KP_MEMRECALL
#define Z_ENGINE_KEY_KP_MEMCLEAR				Z_Engine::Inputs::Key::KP_MEMCLEAR
#define Z_ENGINE_KEY_KP_MEMADD					Z_Engine::Inputs::Key::KP_MEMADD
#define Z_ENGINE_KEY_KP_MEMSUBTRACT				Z_Engine::Inputs::Key::KP_MEMSUBTRACT
#define Z_ENGINE_KEY_KP_MEMMULTIPLY				Z_Engine::Inputs::Key::KP_MEMMULTIPLY
#define Z_ENGINE_KEY_KP_MEMDIVIDE				Z_Engine::Inputs::Key::KP_MEMDIVIDE
#define Z_ENGINE_KEY_KP_PLUSMINUS				Z_Engine::Inputs::Key::KP_PLUSMINUS
#define Z_ENGINE_KEY_KP_CLEAR					Z_Engine::Inputs::Key::KP_CLEAR
#define Z_ENGINE_KEY_KP_CLEARENTRY				Z_Engine::Inputs::Key::KP_CLEARENTRY
#define Z_ENGINE_KEY_KP_BINARY					Z_Engine::Inputs::Key::KP_BINARY
#define Z_ENGINE_KEY_KP_OCTAL					Z_Engine::Inputs::Key::KP_OCTAL
#define Z_ENGINE_KEY_KP_DECIMAL					Z_Engine::Inputs::Key::KP_DECIMAL
#define Z_ENGINE_KEY_KP_HEXADECIMAL				Z_Engine::Inputs::Key::KP_HEXADECIMAL
#define Z_ENGINE_KEY_LCTRL						Z_Engine::Inputs::Key::LCTRL
#define Z_ENGINE_KEY_LSHIFT						Z_Engine::Inputs::Key::LSHIFT
#define Z_ENGINE_KEY_LALT						Z_Engine::Inputs::Key::LALT
#define Z_ENGINE_KEY_LGUI						Z_Engine::Inputs::Key::LGUI
#define Z_ENGINE_KEY_RCTRL						Z_Engine::Inputs::Key::RCTRL
#define Z_ENGINE_KEY_RSHIFT						Z_Engine::Inputs::Key::RSHIFT
#define Z_ENGINE_KEY_RALT						Z_Engine::Inputs::Key::RALT
#define Z_ENGINE_KEY_RGUI						Z_Engine::Inputs::Key::RGUI
#define Z_ENGINE_KEY_MODE						Z_Engine::Inputs::Key::MODE
#define Z_ENGINE_KEY_AUDIONEXT					Z_Engine::Inputs::Key::AUDIONEXT
#define Z_ENGINE_KEY_AUDIOPREV					Z_Engine::Inputs::Key::AUDIOPREV
#define Z_ENGINE_KEY_AUDIOSTOP					Z_Engine::Inputs::Key::AUDIOSTOP
#define Z_ENGINE_KEY_AUDIOPLAY					Z_Engine::Inputs::Key::AUDIOPLAY
#define Z_ENGINE_KEY_AUDIOMUTE					Z_Engine::Inputs::Key::AUDIOMUTE
#define Z_ENGINE_KEY_MEDIASELECT				Z_Engine::Inputs::Key::MEDIASELECT
#define Z_ENGINE_KEY_WWW						Z_Engine::Inputs::Key::WWW
#define Z_ENGINE_KEY_MAIL						Z_Engine::Inputs::Key::MAIL
#define Z_ENGINE_KEY_CALCULATOR					Z_Engine::Inputs::Key::CALCULATOR
#define Z_ENGINE_KEY_COMPUTER					Z_Engine::Inputs::Key::COMPUTER
#define Z_ENGINE_KEY_AC_SEARCH					Z_Engine::Inputs::Key::AC_SEARCH
#define Z_ENGINE_KEY_AC_HOME					Z_Engine::Inputs::Key::AC_HOME
#define Z_ENGINE_KEY_AC_BACK					Z_Engine::Inputs::Key::AC_BACK
#define Z_ENGINE_KEY_AC_FORWARD					Z_Engine::Inputs::Key::AC_FORWARD
#define Z_ENGINE_KEY_AC_STOP					Z_Engine::Inputs::Key::AC_STOP
#define Z_ENGINE_KEY_AC_REFRESH					Z_Engine::Inputs::Key::AC_REFRESH
#define Z_ENGINE_KEY_AC_BOOKMARKS				Z_Engine::Inputs::Key::AC_BOOKMARKS
#define Z_ENGINE_KEY_BRIGHTNESSDOWN				Z_Engine::Inputs::Key::BRIGHTNESSDOWN
#define Z_ENGINE_KEY_BRIGHTNESSUP				Z_Engine::Inputs::Key::BRIGHTNESSUP
#define Z_ENGINE_KEY_DISPLAYSWITCH				Z_Engine::Inputs::Key::DISPLAYSWITCH
#define Z_ENGINE_KEY_KBDILLUMTOGGLE				Z_Engine::Inputs::Key::KBDILLUMTOGGLE
#define Z_ENGINE_KEY_KBDILLUMDOWN				Z_Engine::Inputs::Key::KBDILLUMDOWN
#define Z_ENGINE_KEY_KBDILLUMUP					Z_Engine::Inputs::Key::KBDILLUMUP
#define Z_ENGINE_KEY_EJECT						Z_Engine::Inputs::Key::EJECT
#define Z_ENGINE_KEY_SLEEP						Z_Engine::Inputs::Key::SLEEP
#define Z_ENGINE_KEY_APP1						Z_Engine::Inputs::Key::APP1
#define Z_ENGINE_KEY_APP2						Z_Engine::Inputs::Key::APP2


#define Z_ENGINE_KEY_MOUSE_LEFT		Z_Engine::Inputs::Key::MOUSE_LEFT
#define Z_ENGINE_KEY_MOUSE_RIGHT	Z_Engine::Inputs::Key::MOUSE_RIGHT
#define Z_ENGINE_KEY_MOUSE_WHEEL	Z_Engine::Inputs::Key::MOUSE_WHEEL