
jobs:
- job: CMake_Build
  displayName: 'CMake: Build'
  timeoutInMinutes: 180
  pool:
    name: Windows-OS
    vmImage: windows-2019
  workspace:
    clean: all
  strategy:
    matrix:
        WINDOWS_DEBUG:
          BuildSystem: Windows
          BuildConfiguration: Debug
          BuildPlatform: x64
        WINDOW-RELEASE:
          BuildSystem: Windows
          BuildConfiguration: Release
          BuildPlatform: x64
  
  steps:
  - checkout: self
    clean: true
    submodules: true

  - task: PowerShell@2
    displayName: 'Configure CMake'
    targetType: 'inline'
    workingDirectory: $(Build.SourceDirectory)
    script: 'cmake -S . -B .\out\build -G "Visual Studio 16 2019" -A $(BuildPlatform) -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSPDLOG_BUILD_SHARED=OFF -DBUILD_STATIC_LIBS=ON'
    pwsh: true
  
  - task: PowerShell@2
    displayName: 'CMake Build'
    targetType: 'inline'
    workingDirectory: $(Build.SourceDirectory)
    script: 'cmake --build .\out\build --config $(BuildConfiguration)'
    pwsh: true
    condition: succeeded()
  
