#pragma  once
#include <cstdint>

namespace ZEngine::Inputs {
	
	typedef enum class KeyCode : std::int32_t {

		A				   = 0x004,
		B				   = 0x005,
		C				   = 0x006,
		D				   = 0x007,
		E				   = 0x008,
		F				   = 0x009,
		G				   = 0x00A,
		H				   = 0x00B,
		I				   = 0x00C,
		J				   = 0x00D,
		K				   = 0x00E,
		L				   = 0x00F,
		M				   = 0x010,
		N				   = 0x011,
		O				   = 0x012,
		P				   = 0x013,
		Q				   = 0x014,
		R				   = 0x015,
		S				   = 0x016,
		T				   = 0x017,
		U				   = 0x018,
		V				   = 0x019,
		W				   = 0x01A,
		X				   = 0x01B,
		Y				   = 0x01C,
		Z				   = 0x01D,
		RETURN			   = 0x028,
		ESCAPE			   = 0x029,
		BACKSPACE		   = 0x02A,
		TAB				   = 0x02B,
		SPACE			   = 0x02C,
		MINUS			   = 0x02D,
		EQUALS			   = 0x02E,
		LEFTBRACKET		   = 0x02F,
		RIGHTBRACKET	   = 0x030,
		BACKSLASH		   = 0x031,
		NONUSHASH		   = 0x032,
		SEMICOLON		   = 0x033,
		APOSTROPHE		   = 0x034,
		GRAVE			   = 0x035,
		COMMA			   = 0x036,
		PERIOD			   = 0x037,
		SLASH			   = 0x038,
		CAPSLOCK		   = 0x039,
		F1				   = 0x03A,
		F2				   = 0x03B,
		F3				   = 0x03C,
		F4				   = 0x03D,
		F5				   = 0x03E,
		F6				   = 0x03F,
		F7				   = 0x040,
		F8				   = 0x041,
		F9				   = 0x042,
		F10				   = 0x043,
		F11				   = 0x044,
		F12				   = 0x045,
		PRINTSCREEN		   = 0x046,
		SCROLLLOCK		   = 0x047,
		PAUSE			   = 0x048,
		INSERT			   = 0x049,
		HOME			   = 0x04A,
		PAGEUP			   = 0x04B,
		DELETE			   = 0x04C,
		END				   = 0x04D,
		PAGEDOWN		   = 0x04E,
		RIGHT			   = 0x04F,
		LEFT			   = 0x050,
		DOWN			   = 0x051,
		UP				   = 0x052,
		NUMLOCKCLEAR	   = 0x053,
		KP_DIVIDE		   = 0x054,
		KP_MULTIPLY		   = 0x055,
		KP_MINUS		   = 0x056,
		KP_PLUS			   = 0x057,
		KP_ENTER		   = 0x058,
		KP_1			   = 0x059,
		KP_2			   = 0x05A,
		KP_3			   = 0x05B,
		KP_4			   = 0x05C,
		KP_5			   = 0x05D,
		KP_6			   = 0x05E,
		KP_7			   = 0x05F,
		KP_8			   = 0x060,
		KP_9			   = 0x061,
		KP_0			   = 0x062,
		KP_PERIOD		   = 0x063,
		NONUSBACKSLASH	   = 0x064,
		APPLICATION		   = 0x065,
		POWER			   = 0x066,
		KP_EQUALS		   = 0x067,
		F13				   = 0x068,
		F14				   = 0x069,
		F15				   = 0x06A,
		F16				   = 0x06B,
		F17				   = 0x06C,
		F18				   = 0x06D,
		F19				   = 0x06E,
		F20				   = 0x06F,
		F21				   = 0x070,
		F22				   = 0x071,
		F23				   = 0x072,
		F24				   = 0x073,
		EXECUTE			   = 0x074,
		HELP			   = 0x075,
		MENU			   = 0x076,
		SELECT			   = 0x077,
		STOP			   = 0x078,
		AGAIN			   = 0x079,
		UNDO			   = 0x07A,
		CUT				   = 0x07B,
		COPY			   = 0x07C,
		PASTE			   = 0x07D,
		FIND			   = 0x07E,
		MUTE			   = 0x07F,
		VOLUMEUP		   = 0x080,
		VOLUMEDOWN		   = 0x081,
		KP_COMMA		   = 0x085,
		KP_EQUALSAS400	   = 0x086,
		INTERNATIONAL1	   = 0x087,
		INTERNATIONAL2	   = 0x088,
		INTERNATIONAL3	   = 0x089,
		INTERNATIONAL4	   = 0x08A,
		INTERNATIONAL5	   = 0x08B,
		INTERNATIONAL6	   = 0x08C,
		INTERNATIONAL7	   = 0x08D,
		INTERNATIONAL8	   = 0x08E,
		INTERNATIONAL9	   = 0x08F,
		LANG1			   = 0x090,
		LANG2			   = 0x091,
		LANG3			   = 0x092,
		LANG4			   = 0x093,
		LANG5			   = 0x094,
		LANG6			   = 0x095,
		LANG7			   = 0x096,
		LANG8			   = 0x097,
		LANG9			   = 0x098,
		ALTERASE		   = 0x099,
		SYSREQ			   = 0x09A,
		CANCEL			   = 0x09B,
		CLEAR			   = 0x09C,
		PRIOR			   = 0x09D,
		RETURN2			   = 0x09E,
		SEPARATOR		   = 0x09F,
		OUT				   = 0x0A0,
		OPER			   = 0x0A1,
		CLEARAGAIN		   = 0x0A2,
		CRSEL			   = 0x0A3,
		EXSEL			   = 0x0A4,
		KP_00			   = 0x0B0,
		KP_000			   = 0x0B1,
		THOUSANDSSEPARATOR = 0x0B2,
		DECIMALSEPARATOR   = 0x0B3,
		CURRENCYUNIT       = 0x0B4,
		CURRENCYSUBUNIT    = 0x0B5,
		KP_LEFTPAREN       = 0x0B6,
		KP_RIGHTPAREN      = 0x0B7,
		KP_LEFTBRACE       = 0x0B8,
		KP_RIGHTBRACE      = 0x0B9,
		KP_TAB             = 0x0BA,
		KP_BACKSPACE       = 0x0BB,
		KP_A			   = 0x0BC,
		KP_B			   = 0x0BD,
		KP_C			   = 0x0BE,
		KP_D			   = 0x0BF,
		KP_E			   = 0x0C0,
		KP_F			   = 0x0C1,
		KP_XOR			   = 0x0C2,
		KP_POWER		   = 0x0C3,
		KP_PERCENT		   = 0x0C4,
		KP_LESS			   = 0x0C5,
		KP_GREATER		   = 0x0C6,
		KP_AMPERSAND       = 0x0C7,
		KP_DBLAMPERSAND    = 0x0C8,
		KP_VERTICALBAR     = 0x0C9,
		KP_DBLVERTICALBAR  = 0x0CA,
		KP_COLON		   = 0x0CB,
		KP_HASH			   = 0x0CC,
		KP_SPACE		   = 0x0CD,
		KP_AT			   = 0x0CE,
		KP_EXCLAM		   = 0x0CF,
		KP_MEMSTORE		   = 0x0D0,
		KP_MEMRECALL	   = 0x0D1,
		KP_MEMCLEAR		   = 0x0D2,
		KP_MEMADD		   = 0x0D3,
		KP_MEMSUBTRACT	   = 0x0D4,
		KP_MEMMULTIPLY	   = 0x0D5,
		KP_MEMDIVIDE	   = 0x0D6,
		KP_PLUSMINUS	   = 0x0D7,
		KP_CLEAR		   = 0x0D8,
		KP_CLEARENTRY	   = 0x0D9,
		KP_BINARY		   = 0x0DA,
		KP_OCTAL		   = 0x0DB,
		KP_DECIMAL		   = 0x0DC,
		KP_HEXADECIMAL	   = 0x0DD,
		LCTRL			   = 0x0E0,
		LSHIFT			   = 0x0E1,
		LALT			   = 0x0E2,
		LGUI			   = 0x0E3,
		RCTRL			   = 0x0E4,
		RSHIFT			   = 0x0E5,
		RALT			   = 0x0E6,
		RGUI			   = 0x0E7,
		MODE			   = 0x101,
		AUDIONEXT		   = 0x102,
		AUDIOPREV		   = 0x103,
		AUDIOSTOP		   = 0x104,
		AUDIOPLAY		   = 0x105,
		AUDIOMUTE		   = 0x106,
		MEDIASELECT		   = 0x107,
		WWW				   = 0x108,
		MAIL			   = 0x109,
		CALCULATOR		   = 0x10A,
		COMPUTER		   = 0x10B,
		AC_SEARCH		   = 0x10C,
		AC_HOME			   = 0x10D,
		AC_BACK			   = 0x10E,
		AC_FORWARD		   = 0x10F,
		AC_STOP			   = 0x110,
		AC_REFRESH		   = 0x111,
		AC_BOOKMARKS	   = 0x112,
		BRIGHTNESSDOWN	   = 0x113,
		BRIGHTNESSUP	   = 0x114,
		DISPLAYSWITCH	   = 0x115,
		KBDILLUMTOGGLE	   = 0x116,
		KBDILLUMDOWN	   = 0x117,
		KBDILLUMUP		   = 0x118,
		EJECT			   = 0x119,
		SLEEP			   = 0x11A,
		APP1			   = 0x11B,
		APP2			   = 0x11C,

		MOUSE_LEFT  = 1,
		MOUSE_WHEEL = 2,
		MOUSE_RIGHT = 3,

	} Key;

	typedef enum class GlfwKeyCode : int32_t {
		KEY_UNKNOWN = -1,
		KEY_SPACE = 32,
		KEY_APOSTROPHE = 39,
		KEY_COMMA = 44,
		KEY_MINUS = 45,
		KEY_PERIOD = 46,
		KEY_SLASH = 47,
		KEY_0 = 48,
		KEY_1 = 49,
		KEY_2 = 50,
		KEY_3 = 51,
		KEY_4 = 52,
		KEY_5 = 53,
		KEY_6 = 54,
		KEY_7 = 55,
		KEY_8 = 56,
		KEY_9 = 57,
		KEY_SEMICOLON = 59,
		KEY_EQUAL = 61,
		KEY_A = 65,
		KEY_B = 66,
		KEY_C = 67,
		KEY_D = 68,
		KEY_E = 69,
		KEY_F = 70,
		KEY_G = 71,
		KEY_H = 72,
		KEY_I = 73,
		KEY_J = 74,
		KEY_K = 75,
		KEY_L = 76,
		KEY_M = 77,
		KEY_N = 78,
		KEY_O = 79,
		KEY_P = 80,
		KEY_Q = 81,
		KEY_R = 82,
		KEY_S = 83,
		KEY_T = 84,
		KEY_U = 85,
		KEY_V = 86,
		KEY_W = 87,
		KEY_X = 88,
		KEY_Y = 89,
		KEY_Z = 90,
		KEY_LEFT_BRACKET = 91,
		KEY_BACKSLASH = 92,
		KEY_RIGHT_BRACKET = 93,
		KEY_GRAVE_ACCENT = 96,
		KEY_WORLD_1 = 161,
		KEY_WORLD_2 = 162,
		KEY_ESCAPE = 256,
		KEY_ENTER = 257,
		KEY_TAB = 258,
		KEY_BACKSPACE = 259,
		KEY_INSERT = 260,
		KEY_DELETE = 261,
		KEY_RIGHT = 262,
		KEY_LEFT = 263,
		KEY_DOWN = 264,
		KEY_UP = 265,
		KEY_PAGE_UP = 266,
		KEY_PAGE_DOWN = 267,
		KEY_HOME = 268,
		KEY_END = 269,
		KEY_CAPS_LOCK = 280,
		KEY_SCROLL_LOCK = 281,
		KEY_NUM_LOCK = 282,
		KEY_PRINT_SCREEN = 283,
		KEY_PAUSE = 284,
		KEY_F1 = 290,
		KEY_F2 = 291,
		KEY_F3 = 292,
		KEY_F4 = 293,
		KEY_F5 = 294,
		KEY_F6 = 295,
		KEY_F7 = 296,
		KEY_F8 = 297,
		KEY_F9 = 298,
		KEY_F10 = 299,
		KEY_F11 = 300,
		KEY_F12 = 301,
		KEY_F13 = 302,
		KEY_F14 = 303,
		KEY_F15 = 304,
		KEY_F16 = 305,
		KEY_F17 = 306,
		KEY_F18 = 307,
		KEY_F19 = 308,
		KEY_F20 = 309,
		KEY_F21 = 310,
		KEY_F22 = 311,
		KEY_F23 = 312,
		KEY_F24 = 313,
		KEY_F25 = 314,
		KEY_KP_0 = 320,
		KEY_KP_1 = 321,
		KEY_KP_2 = 322,
		KEY_KP_3 = 323,
		KEY_KP_4 = 324,
		KEY_KP_5 = 325,
		KEY_KP_6 = 326,
		KEY_KP_7 = 327,
		KEY_KP_8 = 328,
		KEY_KP_9 = 329,
		KEY_KP_DECIMAL = 330,
		KEY_KP_DIVIDE = 331,
		KEY_KP_MULTIPLY = 332,
		KEY_KP_SUBTRACT = 333,
		KEY_KP_ADD = 334,
		KEY_KP_ENTER = 335,
		KEY_KP_EQUAL = 336,
		KEY_LEFT_SHIFT = 340,
		KEY_LEFT_CONTROL = 341,
		KEY_LEFT_ALT = 342,
		KEY_LEFT_SUPER = 343,
		KEY_RIGHT_SHIFT = 344,
		KEY_RIGHT_CONTROL = 345,
		KEY_RIGHT_ALT = 346,
		KEY_RIGHT_SUPER = 347,
		KEY_MENU = 348,
		MOUSE_BUTTON_LEFT = 0,
		MOUSE_BUTTON_RIGHT = 1,
		MOUSE_BUTTON_MIDDLE = 2,
		MOUSE_BUTTON_4 = 3,
		MOUSE_BUTTON_5 = 4,
		MOUSE_BUTTON_6 = 5,
		MOUSE_BUTTON_7 = 6,
		MOUSE_BUTTON_8 = 7

	} GlfwKey;
}

#ifdef ZENGINE_KEY_MAPPING_SDL
	#define ZEngine_KEY_A							ZEngine::Inputs::Key::A
	#define ZEngine_KEY_B							ZEngine::Inputs::Key::B
	#define ZEngine_KEY_C							ZEngine::Inputs::Key::C
	#define ZEngine_KEY_D							ZEngine::Inputs::Key::D
	#define ZEngine_KEY_E							ZEngine::Inputs::Key::E
	#define ZEngine_KEY_F							ZEngine::Inputs::Key::F
	#define ZEngine_KEY_G							ZEngine::Inputs::Key::G
	#define ZEngine_KEY_H							ZEngine::Inputs::Key::H
	#define ZEngine_KEY_I							ZEngine::Inputs::Key::I
	#define ZEngine_KEY_J							ZEngine::Inputs::Key::J
	#define ZEngine_KEY_K							ZEngine::Inputs::Key::K
	#define ZEngine_KEY_L							ZEngine::Inputs::Key::L
	#define ZEngine_KEY_M							ZEngine::Inputs::Key::M
	#define ZEngine_KEY_N							ZEngine::Inputs::Key::N
	#define ZEngine_KEY_O							ZEngine::Inputs::Key::O
	#define ZEngine_KEY_P							ZEngine::Inputs::Key::P
	#define ZEngine_KEY_Q							ZEngine::Inputs::Key::Q
	#define ZEngine_KEY_R							ZEngine::Inputs::Key::R
	#define ZEngine_KEY_S							ZEngine::Inputs::Key::S
	#define ZEngine_KEY_T							ZEngine::Inputs::Key::T
	#define ZEngine_KEY_U							ZEngine::Inputs::Key::U
	#define ZEngine_KEY_V							ZEngine::Inputs::Key::V
	#define ZEngine_KEY_W							ZEngine::Inputs::Key::W
	#define ZEngine_KEY_X							ZEngine::Inputs::Key::X
	#define ZEngine_KEY_Y							ZEngine::Inputs::Key::Y
	#define ZEngine_KEY_Z							ZEngine::Inputs::Key::Z
	#define ZEngine_KEY_RETURN						ZEngine::Inputs::Key::RETURN
	#define ZEngine_KEY_ESCAPE						ZEngine::Inputs::Key::ESCAPE
	#define ZEngine_KEY_BACKSPACE					ZEngine::Inputs::Key::BACKSPACE
	#define ZEngine_KEY_TAB						ZEngine::Inputs::Key::TAB
	#define ZEngine_KEY_SPACE						ZEngine::Inputs::Key::SPACE
	#define ZEngine_KEY_MINUS						ZEngine::Inputs::Key::MINUS
	#define ZEngine_KEY_EQUALS						ZEngine::Inputs::Key::EQUALS
	#define ZEngine_KEY_LEFTBRACKET				ZEngine::Inputs::Key::LEFTBRACKET
	#define ZEngine_KEY_RIGHTBRACKET				ZEngine::Inputs::Key::RIGHTBRACKET
	#define ZEngine_KEY_BACKSLASH					ZEngine::Inputs::Key::BACKSLASH
	#define ZEngine_KEY_NONUSHASH					ZEngine::Inputs::Key::NONUSHASH
	#define ZEngine_KEY_SEMICOLON					ZEngine::Inputs::Key::SEMICOLON
	#define ZEngine_KEY_APOSTROPHE					ZEngine::Inputs::Key::APOSTROPHE
	#define ZEngine_KEY_GRAVE						ZEngine::Inputs::Key::GRAVE
	#define ZEngine_KEY_COMMA						ZEngine::Inputs::Key::COMMA
	#define ZEngine_KEY_PERIOD						ZEngine::Inputs::Key::PERIOD
	#define ZEngine_KEY_SLASH						ZEngine::Inputs::Key::SLASH
	#define ZEngine_KEY_CAPSLOCK					ZEngine::Inputs::Key::CAPSLOCK
	#define ZEngine_KEY_F1							ZEngine::Inputs::Key::F1
	#define ZEngine_KEY_F2							ZEngine::Inputs::Key::F2
	#define ZEngine_KEY_F3							ZEngine::Inputs::Key::F3
	#define ZEngine_KEY_F4							ZEngine::Inputs::Key::F4
	#define ZEngine_KEY_F5							ZEngine::Inputs::Key::F5
	#define ZEngine_KEY_F6							ZEngine::Inputs::Key::F6
	#define ZEngine_KEY_F7							ZEngine::Inputs::Key::F7
	#define ZEngine_KEY_F8							ZEngine::Inputs::Key::F8
	#define ZEngine_KEY_F9							ZEngine::Inputs::Key::F9
	#define ZEngine_KEY_F10						ZEngine::Inputs::Key::F10
	#define ZEngine_KEY_F11						ZEngine::Inputs::Key::F11
	#define ZEngine_KEY_F12						ZEngine::Inputs::Key::F12
	#define ZEngine_KEY_PRINTSCREEN				ZEngine::Inputs::Key::PRINTSCREEN
	#define ZEngine_KEY_SCROLLLOCK					ZEngine::Inputs::Key::SCROLLLOCK
	#define ZEngine_KEY_PAUSE						ZEngine::Inputs::Key::PAUSE
	#define ZEngine_KEY_INSERT						ZEngine::Inputs::Key::INSERT
	#define ZEngine_KEY_HOME						ZEngine::Inputs::Key::HOME
	#define ZEngine_KEY_PAGEUP						ZEngine::Inputs::Key::PAGEUP
	#define ZEngine_KEY_DELETE						ZEngine::Inputs::Key::DELETE
	#define ZEngine_KEY_END						ZEngine::Inputs::Key::END
	#define ZEngine_KEY_PAGEDOWN					ZEngine::Inputs::Key::PAGEDOWN
	#define ZEngine_KEY_RIGHT						ZEngine::Inputs::Key::RIGHT
	#define ZEngine_KEY_LEFT						ZEngine::Inputs::Key::LEFT
	#define ZEngine_KEY_DOWN						ZEngine::Inputs::Key::DOWN
	#define ZEngine_KEY_UP							ZEngine::Inputs::Key::UP
	#define ZEngine_KEY_NUMLOCKCLEAR				ZEngine::Inputs::Key::NUMLOCKCLEAR
	#define ZEngine_KEY_KP_DIVIDE					ZEngine::Inputs::Key::KP_DIVIDE
	#define ZEngine_KEY_KP_MULTIPLY				ZEngine::Inputs::Key::KP_MULTIPLY
	#define ZEngine_KEY_KP_MINUS					ZEngine::Inputs::Key::KP_MINUS
	#define ZEngine_KEY_KP_PLUS					ZEngine::Inputs::Key::KP_PLUS
	#define ZEngine_KEY_KP_ENTER					ZEngine::Inputs::Key::KP_ENTER
	#define ZEngine_KEY_KP_1						ZEngine::Inputs::Key::KP_1
	#define ZEngine_KEY_KP_2						ZEngine::Inputs::Key::KP_2
	#define ZEngine_KEY_KP_3						ZEngine::Inputs::Key::KP_3
	#define ZEngine_KEY_KP_4						ZEngine::Inputs::Key::KP_4
	#define ZEngine_KEY_KP_5						ZEngine::Inputs::Key::KP_5
	#define ZEngine_KEY_KP_6						ZEngine::Inputs::Key::KP_6
	#define ZEngine_KEY_KP_7						ZEngine::Inputs::Key::KP_7
	#define ZEngine_KEY_KP_8						ZEngine::Inputs::Key::KP_8
	#define ZEngine_KEY_KP_9						ZEngine::Inputs::Key::KP_9
	#define ZEngine_KEY_KP_0						ZEngine::Inputs::Key::KP_0
	#define ZEngine_KEY_KP_PERIOD					ZEngine::Inputs::Key::KP_PERIOD
	#define ZEngine_KEY_NONUSBACKSLASH				ZEngine::Inputs::Key::NONUSBACKSLASH
	#define ZEngine_KEY_APPLICATION				ZEngine::Inputs::Key::APPLICATION
	#define ZEngine_KEY_POWER						ZEngine::Inputs::Key::POWER
	#define ZEngine_KEY_KP_EQUALS					ZEngine::Inputs::Key::KP_EQUALS
	#define ZEngine_KEY_F13						ZEngine::Inputs::Key::F13
	#define ZEngine_KEY_F14						ZEngine::Inputs::Key::F14
	#define ZEngine_KEY_F15						ZEngine::Inputs::Key::F15
	#define ZEngine_KEY_F16						ZEngine::Inputs::Key::F16
	#define ZEngine_KEY_F17						ZEngine::Inputs::Key::F17
	#define ZEngine_KEY_F18						ZEngine::Inputs::Key::F18
	#define ZEngine_KEY_F19						ZEngine::Inputs::Key::F19
	#define ZEngine_KEY_F20						ZEngine::Inputs::Key::F20
	#define ZEngine_KEY_F21						ZEngine::Inputs::Key::F21
	#define ZEngine_KEY_F22						ZEngine::Inputs::Key::F22
	#define ZEngine_KEY_F23						ZEngine::Inputs::Key::F23
	#define ZEngine_KEY_F24						ZEngine::Inputs::Key::F24
	#define ZEngine_KEY_EXECUTE					ZEngine::Inputs::Key::EXECUTE
	#define ZEngine_KEY_HELP						ZEngine::Inputs::Key::HELP
	#define ZEngine_KEY_MENU						ZEngine::Inputs::Key::MENU
	#define ZEngine_KEY_SELECT						ZEngine::Inputs::Key::SELECT
	#define ZEngine_KEY_STOP						ZEngine::Inputs::Key::STOP
	#define ZEngine_KEY_AGAIN						ZEngine::Inputs::Key::AGAIN
	#define ZEngine_KEY_UNDO						ZEngine::Inputs::Key::UNDO
	#define ZEngine_KEY_CUT						ZEngine::Inputs::Key::CUT
	#define ZEngine_KEY_COPY						ZEngine::Inputs::Key::COPY
	#define ZEngine_KEY_PASTE						ZEngine::Inputs::Key::PASTE
	#define ZEngine_KEY_FIND						ZEngine::Inputs::Key::FIND
	#define ZEngine_KEY_MUTE						ZEngine::Inputs::Key::MUTE
	#define ZEngine_KEY_VOLUMEUP					ZEngine::Inputs::Key::VOLUMEUP
	#define ZEngine_KEY_VOLUMEDOWN					ZEngine::Inputs::Key::VOLUMEDOWN
	#define ZEngine_KEY_KP_COMMA					ZEngine::Inputs::Key::KP_COMMA
	#define ZEngine_KEY_KP_EQUALSAS400				ZEngine::Inputs::Key::KP_EQUALSAS400
	#define ZEngine_KEY_INTERNATIONAL1				ZEngine::Inputs::Key::INTERNATIONAL1
	#define ZEngine_KEY_INTERNATIONAL2				ZEngine::Inputs::Key::INTERNATIONAL2
	#define ZEngine_KEY_INTERNATIONAL3				ZEngine::Inputs::Key::INTERNATIONAL3
	#define ZEngine_KEY_INTERNATIONAL4				ZEngine::Inputs::Key::INTERNATIONAL4
	#define ZEngine_KEY_INTERNATIONAL5				ZEngine::Inputs::Key::INTERNATIONAL5
	#define ZEngine_KEY_INTERNATIONAL6				ZEngine::Inputs::Key::INTERNATIONAL6
	#define ZEngine_KEY_INTERNATIONAL7				ZEngine::Inputs::Key::INTERNATIONAL7
	#define ZEngine_KEY_INTERNATIONAL8				ZEngine::Inputs::Key::INTERNATIONAL8
	#define ZEngine_KEY_INTERNATIONAL9				ZEngine::Inputs::Key::INTERNATIONAL9
	#define ZEngine_KEY_LANG1						ZEngine::Inputs::Key::LANG1
	#define ZEngine_KEY_LANG2						ZEngine::Inputs::Key::LANG2
	#define ZEngine_KEY_LANG3						ZEngine::Inputs::Key::LANG3
	#define ZEngine_KEY_LANG4						ZEngine::Inputs::Key::LANG4
	#define ZEngine_KEY_LANG5						ZEngine::Inputs::Key::LANG5
	#define ZEngine_KEY_LANG6						ZEngine::Inputs::Key::LANG6
	#define ZEngine_KEY_LANG7						ZEngine::Inputs::Key::LANG7
	#define ZEngine_KEY_LANG8						ZEngine::Inputs::Key::LANG8
	#define ZEngine_KEY_LANG9						ZEngine::Inputs::Key::LANG9
	#define ZEngine_KEY_ALTERASE					ZEngine::Inputs::Key::ALTERASE
	#define ZEngine_KEY_SYSREQ						ZEngine::Inputs::Key::SYSREQ
	#define ZEngine_KEY_CANCEL						ZEngine::Inputs::Key::CANCEL
	#define ZEngine_KEY_CLEAR						ZEngine::Inputs::Key::CLEAR
	#define ZEngine_KEY_PRIOR						ZEngine::Inputs::Key::PRIOR
	#define ZEngine_KEY_RETURN2					ZEngine::Inputs::Key::RETURN2
	#define ZEngine_KEY_SEPARATOR					ZEngine::Inputs::Key::SEPARATOR
	#define ZEngine_KEY_OUT						ZEngine::Inputs::Key::OUT
	#define ZEngine_KEY_OPER						ZEngine::Inputs::Key::OPER
	#define ZEngine_KEY_CLEARAGAIN					ZEngine::Inputs::Key::CLEARAGAIN
	#define ZEngine_KEY_CRSEL						ZEngine::Inputs::Key::CRSEL
	#define ZEngine_KEY_EXSEL						ZEngine::Inputs::Key::EXSEL
	#define ZEngine_KEY_KP_00						ZEngine::Inputs::Key::KP_00
	#define ZEngine_KEY_KP_000						ZEngine::Inputs::Key::KP_000
	#define ZEngine_KEY_THOUSANDSSEPARATOR			ZEngine::Inputs::Key::THOUSANDSSEPARATOR
	#define ZEngine_KEY_DECIMALSEPARATOR			ZEngine::Inputs::Key::DECIMALSEPARATOR
	#define ZEngine_KEY_CURRENCYUNIT				ZEngine::Inputs::Key::CURRENCYUNIT
	#define ZEngine_KEY_CURRENCYSUBUNIT			ZEngine::Inputs::Key::CURRENCYSUBUNIT
	#define ZEngine_KEY_KP_LEFTPAREN				ZEngine::Inputs::Key::KP_LEFTPAREN
	#define ZEngine_KEY_KP_RIGHTPAREN				ZEngine::Inputs::Key::KP_RIGHTPAREN
	#define ZEngine_KEY_KP_LEFTBRACE				ZEngine::Inputs::Key::KP_LEFTBRACE
	#define ZEngine_KEY_KP_RIGHTBRACE				ZEngine::Inputs::Key::KP_RIGHTBRACE
	#define ZEngine_KEY_KP_TAB						ZEngine::Inputs::Key::KP_TAB
	#define ZEngine_KEY_KP_BACKSPACE				ZEngine::Inputs::Key::KP_BACKSPACE
	#define ZEngine_KEY_KP_A						ZEngine::Inputs::Key::KP_A
	#define ZEngine_KEY_KP_B						ZEngine::Inputs::Key::KP_B
	#define ZEngine_KEY_KP_C						ZEngine::Inputs::Key::KP_C
	#define ZEngine_KEY_KP_D						ZEngine::Inputs::Key::KP_D
	#define ZEngine_KEY_KP_E						ZEngine::Inputs::Key::KP_E
	#define ZEngine_KEY_KP_F						ZEngine::Inputs::Key::KP_F
	#define ZEngine_KEY_KP_XOR						ZEngine::Inputs::Key::KP_XOR
	#define ZEngine_KEY_KP_POWER					ZEngine::Inputs::Key::KP_POWER
	#define ZEngine_KEY_KP_PERCENT					ZEngine::Inputs::Key::KP_PERCENT
	#define ZEngine_KEY_KP_LESS					ZEngine::Inputs::Key::KP_LESS
	#define ZEngine_KEY_KP_GREATER					ZEngine::Inputs::Key::KP_GREATER
	#define ZEngine_KEY_KP_AMPERSAND				ZEngine::Inputs::Key::KP_AMPERSAND
	#define ZEngine_KEY_KP_DBLAMPERSAND			ZEngine::Inputs::Key::KP_DBLAMPERSAND
	#define ZEngine_KEY_KP_VERTICALBAR				ZEngine::Inputs::Key::KP_VERTICALBAR
	#define ZEngine_KEY_KP_DBLVERTICALBAR			ZEngine::Inputs::Key::KP_DBLVERTICALBAR
	#define ZEngine_KEY_KP_COLON					ZEngine::Inputs::Key::KP_COLON
	#define ZEngine_KEY_KP_HASH					ZEngine::Inputs::Key::KP_HASH
	#define ZEngine_KEY_KP_SPACE					ZEngine::Inputs::Key::KP_SPACE
	#define ZEngine_KEY_KP_AT						ZEngine::Inputs::Key::KP_AT
	#define ZEngine_KEY_KP_EXCLAM					ZEngine::Inputs::Key::KP_EXCLAM
	#define ZEngine_KEY_KP_MEMSTORE				ZEngine::Inputs::Key::KP_MEMSTORE
	#define ZEngine_KEY_KP_MEMRECALL				ZEngine::Inputs::Key::KP_MEMRECALL
	#define ZEngine_KEY_KP_MEMCLEAR				ZEngine::Inputs::Key::KP_MEMCLEAR
	#define ZEngine_KEY_KP_MEMADD					ZEngine::Inputs::Key::KP_MEMADD
	#define ZEngine_KEY_KP_MEMSUBTRACT				ZEngine::Inputs::Key::KP_MEMSUBTRACT
	#define ZEngine_KEY_KP_MEMMULTIPLY				ZEngine::Inputs::Key::KP_MEMMULTIPLY
	#define ZEngine_KEY_KP_MEMDIVIDE				ZEngine::Inputs::Key::KP_MEMDIVIDE
	#define ZEngine_KEY_KP_PLUSMINUS				ZEngine::Inputs::Key::KP_PLUSMINUS
	#define ZEngine_KEY_KP_CLEAR					ZEngine::Inputs::Key::KP_CLEAR
	#define ZEngine_KEY_KP_CLEARENTRY				ZEngine::Inputs::Key::KP_CLEARENTRY
	#define ZEngine_KEY_KP_BINARY					ZEngine::Inputs::Key::KP_BINARY
	#define ZEngine_KEY_KP_OCTAL					ZEngine::Inputs::Key::KP_OCTAL
	#define ZEngine_KEY_KP_DECIMAL					ZEngine::Inputs::Key::KP_DECIMAL
	#define ZEngine_KEY_KP_HEXADECIMAL				ZEngine::Inputs::Key::KP_HEXADECIMAL
	#define ZEngine_KEY_LCTRL						ZEngine::Inputs::Key::LCTRL
	#define ZEngine_KEY_LSHIFT						ZEngine::Inputs::Key::LSHIFT
	#define ZEngine_KEY_LALT						ZEngine::Inputs::Key::LALT
	#define ZEngine_KEY_LGUI						ZEngine::Inputs::Key::LGUI
	#define ZEngine_KEY_RCTRL						ZEngine::Inputs::Key::RCTRL
	#define ZEngine_KEY_RSHIFT						ZEngine::Inputs::Key::RSHIFT
	#define ZEngine_KEY_RALT						ZEngine::Inputs::Key::RALT
	#define ZEngine_KEY_RGUI						ZEngine::Inputs::Key::RGUI
	#define ZEngine_KEY_MODE						ZEngine::Inputs::Key::MODE
	#define ZEngine_KEY_AUDIONEXT					ZEngine::Inputs::Key::AUDIONEXT
	#define ZEngine_KEY_AUDIOPREV					ZEngine::Inputs::Key::AUDIOPREV
	#define ZEngine_KEY_AUDIOSTOP					ZEngine::Inputs::Key::AUDIOSTOP
	#define ZEngine_KEY_AUDIOPLAY					ZEngine::Inputs::Key::AUDIOPLAY
	#define ZEngine_KEY_AUDIOMUTE					ZEngine::Inputs::Key::AUDIOMUTE
	#define ZEngine_KEY_MEDIASELECT				ZEngine::Inputs::Key::MEDIASELECT
	#define ZEngine_KEY_WWW						ZEngine::Inputs::Key::WWW
	#define ZEngine_KEY_MAIL						ZEngine::Inputs::Key::MAIL
	#define ZEngine_KEY_CALCULATOR					ZEngine::Inputs::Key::CALCULATOR
	#define ZEngine_KEY_COMPUTER					ZEngine::Inputs::Key::COMPUTER
	#define ZEngine_KEY_AC_SEARCH					ZEngine::Inputs::Key::AC_SEARCH
	#define ZEngine_KEY_AC_HOME					ZEngine::Inputs::Key::AC_HOME
	#define ZEngine_KEY_AC_BACK					ZEngine::Inputs::Key::AC_BACK
	#define ZEngine_KEY_AC_FORWARD					ZEngine::Inputs::Key::AC_FORWARD
	#define ZEngine_KEY_AC_STOP					ZEngine::Inputs::Key::AC_STOP
	#define ZEngine_KEY_AC_REFRESH					ZEngine::Inputs::Key::AC_REFRESH
	#define ZEngine_KEY_AC_BOOKMARKS				ZEngine::Inputs::Key::AC_BOOKMARKS
	#define ZEngine_KEY_BRIGHTNESSDOWN				ZEngine::Inputs::Key::BRIGHTNESSDOWN
	#define ZEngine_KEY_BRIGHTNESSUP				ZEngine::Inputs::Key::BRIGHTNESSUP
	#define ZEngine_KEY_DISPLAYSWITCH				ZEngine::Inputs::Key::DISPLAYSWITCH
	#define ZEngine_KEY_KBDILLUMTOGGLE				ZEngine::Inputs::Key::KBDILLUMTOGGLE
	#define ZEngine_KEY_KBDILLUMDOWN				ZEngine::Inputs::Key::KBDILLUMDOWN
	#define ZEngine_KEY_KBDILLUMUP					ZEngine::Inputs::Key::KBDILLUMUP
	#define ZEngine_KEY_EJECT						ZEngine::Inputs::Key::EJECT
	#define ZEngine_KEY_SLEEP						ZEngine::Inputs::Key::SLEEP
	#define ZEngine_KEY_APP1						ZEngine::Inputs::Key::APP1
	#define ZEngine_KEY_APP2						ZEngine::Inputs::Key::APP2


	#define ZEngine_KEY_MOUSE_LEFT		ZEngine::Inputs::Key::MOUSE_LEFT
	#define ZEngine_KEY_MOUSE_RIGHT	ZEngine::Inputs::Key::MOUSE_RIGHT
	#define ZEngine_KEY_MOUSE_WHEEL	ZEngine::Inputs::Key::MOUSE_WHEEL

#else 

	#define ZENGINE_KEY_UNKNOWN						ZEngine::Inputs::GlfwKey::KEY_UNKNOWN
	#define ZENGINE_KEY_SPACE						ZEngine::Inputs::GlfwKey::KEY_SPACE
	#define ZENGINE_KEY_APOSTROPHE					ZEngine::Inputs::GlfwKey::KEY_APOSTROPHE
	#define ZENGINE_KEY_COMMA						ZEngine::Inputs::GlfwKey::KEY_COMMA
	#define ZENGINE_KEY_MINUS						ZEngine::Inputs::GlfwKey::KEY_MINUS
	#define ZENGINE_KEY_PERIOD						ZEngine::Inputs::GlfwKey::KEY_PERIOD
	#define ZENGINE_KEY_SLASH						ZEngine::Inputs::GlfwKey::KEY_SLASH
	#define ZENGINE_KEY_0							ZEngine::Inputs::GlfwKey::KEY_0
	#define ZENGINE_KEY_1							ZEngine::Inputs::GlfwKey::KEY_1
	#define ZENGINE_KEY_2							ZEngine::Inputs::GlfwKey::KEY_2
	#define ZENGINE_KEY_3							ZEngine::Inputs::GlfwKey::KEY_3
	#define ZENGINE_KEY_4							ZEngine::Inputs::GlfwKey::KEY_4
	#define ZENGINE_KEY_5							ZEngine::Inputs::GlfwKey::KEY_5
	#define ZENGINE_KEY_6							ZEngine::Inputs::GlfwKey::KEY_6
	#define ZENGINE_KEY_7							ZEngine::Inputs::GlfwKey::KEY_7
	#define ZENGINE_KEY_8							ZEngine::Inputs::GlfwKey::KEY_8
	#define ZENGINE_KEY_9							ZEngine::Inputs::GlfwKey::KEY_9
	#define ZENGINE_KEY_SEMICOLON					ZEngine::Inputs::GlfwKey::KEY_SEMICOLON
	#define ZENGINE_KEY_EQUAL						ZEngine::Inputs::GlfwKey::KEY_EQUAL
	#define ZENGINE_KEY_A							ZEngine::Inputs::GlfwKey::KEY_A
	#define ZENGINE_KEY_B							ZEngine::Inputs::GlfwKey::KEY_B
	#define ZENGINE_KEY_C							ZEngine::Inputs::GlfwKey::KEY_C
	#define ZENGINE_KEY_D							ZEngine::Inputs::GlfwKey::KEY_D
	#define ZENGINE_KEY_E							ZEngine::Inputs::GlfwKey::KEY_E
	#define ZENGINE_KEY_F							ZEngine::Inputs::GlfwKey::KEY_F
	#define ZENGINE_KEY_G							ZEngine::Inputs::GlfwKey::KEY_G
	#define ZENGINE_KEY_H							ZEngine::Inputs::GlfwKey::KEY_H
	#define ZENGINE_KEY_I							ZEngine::Inputs::GlfwKey::KEY_I
	#define ZENGINE_KEY_J							ZEngine::Inputs::GlfwKey::KEY_J
	#define ZENGINE_KEY_K							ZEngine::Inputs::GlfwKey::KEY_K
	#define ZENGINE_KEY_L							ZEngine::Inputs::GlfwKey::KEY_L
	#define ZENGINE_KEY_M							ZEngine::Inputs::GlfwKey::KEY_M
	#define ZENGINE_KEY_N							ZEngine::Inputs::GlfwKey::KEY_N
	#define ZENGINE_KEY_O							ZEngine::Inputs::GlfwKey::KEY_O
	#define ZENGINE_KEY_P							ZEngine::Inputs::GlfwKey::KEY_P
	#define ZENGINE_KEY_Q							ZEngine::Inputs::GlfwKey::KEY_Q
	#define ZENGINE_KEY_R							ZEngine::Inputs::GlfwKey::KEY_R
	#define ZENGINE_KEY_S							ZEngine::Inputs::GlfwKey::KEY_S
	#define ZENGINE_KEY_T							ZEngine::Inputs::GlfwKey::KEY_T
	#define ZENGINE_KEY_U							ZEngine::Inputs::GlfwKey::KEY_U
	#define ZENGINE_KEY_V							ZEngine::Inputs::GlfwKey::KEY_V
	#define ZENGINE_KEY_W							ZEngine::Inputs::GlfwKey::KEY_W
	#define ZENGINE_KEY_X							ZEngine::Inputs::GlfwKey::KEY_X
	#define ZENGINE_KEY_Y							ZEngine::Inputs::GlfwKey::KEY_Y
	#define ZENGINE_KEY_Z							ZEngine::Inputs::GlfwKey::KEY_Z
	#define ZENGINE_KEY_LEFT_BRACKET				ZEngine::Inputs::GlfwKey::KEY_LEFT_BRACKET
	#define ZENGINE_KEY_BACKSLASH					ZEngine::Inputs::GlfwKey::KEY_BACKSLASH
	#define ZENGINE_KEY_RIGHT_BRACKET				ZEngine::Inputs::GlfwKey::KEY_RIGHT_BRACKET
	#define ZENGINE_KEY_GRAVE_ACCENT				ZEngine::Inputs::GlfwKey::KEY_GRAVE_ACCENT
	#define ZENGINE_KEY_WORLD_1						ZEngine::Inputs::GlfwKey::KEY_WORLD_1
	#define ZENGINE_KEY_WORLD_2						ZEngine::Inputs::GlfwKey::KEY_WORLD_2
	#define ZENGINE_KEY_ESCAPE						ZEngine::Inputs::GlfwKey::KEY_ESCAPE
	#define ZENGINE_KEY_ENTER						ZEngine::Inputs::GlfwKey::KEY_ENTER
	#define ZENGINE_KEY_TAB							ZEngine::Inputs::GlfwKey::KEY_TAB
	#define ZENGINE_KEY_BACKSPACE					ZEngine::Inputs::GlfwKey::KEY_BACKSPACE
	#define ZENGINE_KEY_INSERT						ZEngine::Inputs::GlfwKey::KEY_INSERT
	#define ZENGINE_KEY_DELETE						ZEngine::Inputs::GlfwKey::KEY_DELETE
	#define ZENGINE_KEY_RIGHT						ZEngine::Inputs::GlfwKey::KEY_RIGHT
	#define ZENGINE_KEY_LEFT						ZEngine::Inputs::GlfwKey::KEY_LEFT
	#define ZENGINE_KEY_DOWN						ZEngine::Inputs::GlfwKey::KEY_DOWN
	#define ZENGINE_KEY_UP							ZEngine::Inputs::GlfwKey::KEY_UP
	#define ZENGINE_KEY_PAGE_UP						ZEngine::Inputs::GlfwKey::KEY_PAGE_UP
	#define ZENGINE_KEY_PAGE_DOWN					ZEngine::Inputs::GlfwKey::KEY_PAGE_DOWN
	#define ZENGINE_KEY_HOME						ZEngine::Inputs::GlfwKey::KEY_HOME
	#define ZENGINE_KEY_END							ZEngine::Inputs::GlfwKey::KEY_END
	#define ZENGINE_KEY_CAPS_LOCK					ZEngine::Inputs::GlfwKey::KEY_CAPS_LOCK
	#define ZENGINE_KEY_SCROLL_LOCK					ZEngine::Inputs::GlfwKey::KEY_SCROLL_LOCK
	#define ZENGINE_KEY_NUM_LOCK					ZEngine::Inputs::GlfwKey::KEY_NUM_LOCK
	#define ZENGINE_KEY_PRINT_SCREEN				ZEngine::Inputs::GlfwKey::KEY_PRINT_SCREEN
	#define ZENGINE_KEY_PAUSE						ZEngine::Inputs::GlfwKey::KEY_PAUSE
	#define ZENGINE_KEY_F1							ZEngine::Inputs::GlfwKey::KEY_F1
	#define ZENGINE_KEY_F2							ZEngine::Inputs::GlfwKey::KEY_F2
	#define ZENGINE_KEY_F3							ZEngine::Inputs::GlfwKey::KEY_F3
	#define ZENGINE_KEY_F4							ZEngine::Inputs::GlfwKey::KEY_F4
	#define ZENGINE_KEY_F5							ZEngine::Inputs::GlfwKey::KEY_F5
	#define ZENGINE_KEY_F6							ZEngine::Inputs::GlfwKey::KEY_F6
	#define ZENGINE_KEY_F7							ZEngine::Inputs::GlfwKey::KEY_F7
	#define ZENGINE_KEY_F8							ZEngine::Inputs::GlfwKey::KEY_F8
	#define ZENGINE_KEY_F9							ZEngine::Inputs::GlfwKey::KEY_F9
	#define ZENGINE_KEY_F10							ZEngine::Inputs::GlfwKey::KEY_F10
	#define ZENGINE_KEY_F11							ZEngine::Inputs::GlfwKey::KEY_F11
	#define ZENGINE_KEY_F12							ZEngine::Inputs::GlfwKey::KEY_F12
	#define ZENGINE_KEY_F13							ZEngine::Inputs::GlfwKey::KEY_F13
	#define ZENGINE_KEY_F14							ZEngine::Inputs::GlfwKey::KEY_F14
	#define ZENGINE_KEY_F15							ZEngine::Inputs::GlfwKey::KEY_F15
	#define ZENGINE_KEY_F16							ZEngine::Inputs::GlfwKey::KEY_F16
	#define ZENGINE_KEY_F17							ZEngine::Inputs::GlfwKey::KEY_F17
	#define ZENGINE_KEY_F18							ZEngine::Inputs::GlfwKey::KEY_F18
	#define ZENGINE_KEY_F19							ZEngine::Inputs::GlfwKey::KEY_F19
	#define ZENGINE_KEY_F20							ZEngine::Inputs::GlfwKey::KEY_F20
	#define ZENGINE_KEY_F21							ZEngine::Inputs::GlfwKey::KEY_F21
	#define ZENGINE_KEY_F22							ZEngine::Inputs::GlfwKey::KEY_F22
	#define ZENGINE_KEY_F23							ZEngine::Inputs::GlfwKey::KEY_F23
	#define ZENGINE_KEY_F24							ZEngine::Inputs::GlfwKey::KEY_F24
	#define ZENGINE_KEY_F25							ZEngine::Inputs::GlfwKey::KEY_F25
	#define ZENGINE_KEY_KP_0						ZEngine::Inputs::GlfwKey::KEY_KP_0
	#define ZENGINE_KEY_KP_1						ZEngine::Inputs::GlfwKey::KEY_KP_1
	#define ZENGINE_KEY_KP_2						ZEngine::Inputs::GlfwKey::KEY_KP_2
	#define ZENGINE_KEY_KP_3						ZEngine::Inputs::GlfwKey::KEY_KP_3
	#define ZENGINE_KEY_KP_4						ZEngine::Inputs::GlfwKey::KEY_KP_4
	#define ZENGINE_KEY_KP_5						ZEngine::Inputs::GlfwKey::KEY_KP_5
	#define ZENGINE_KEY_KP_6						ZEngine::Inputs::GlfwKey::KEY_KP_6
	#define ZENGINE_KEY_KP_7						ZEngine::Inputs::GlfwKey::KEY_KP_7
	#define ZENGINE_KEY_KP_8						ZEngine::Inputs::GlfwKey::KEY_KP_8
	#define ZENGINE_KEY_KP_9						ZEngine::Inputs::GlfwKey::KEY_KP_9
	#define ZENGINE_KEY_KP_DECIMAL					ZEngine::Inputs::GlfwKey::KEY_KP_DECIMAL
	#define ZENGINE_KEY_KP_DIVIDE					ZEngine::Inputs::GlfwKey::KEY_KP_DIVIDE
	#define ZENGINE_KEY_KP_MULTIPLY					ZEngine::Inputs::GlfwKey::KEY_KP_MULTIPLY
	#define ZENGINE_KEY_KP_SUBTRACT					ZEngine::Inputs::GlfwKey::KEY_KP_SUBTRACT
	#define ZENGINE_KEY_KP_ADD						ZEngine::Inputs::GlfwKey::KEY_KP_ADD
	#define ZENGINE_KEY_KP_ENTER					ZEngine::Inputs::GlfwKey::KEY_KP_ENTER
	#define ZENGINE_KEY_KP_EQUAL					ZEngine::Inputs::GlfwKey::KEY_KP_EQUAL
	#define ZENGINE_KEY_LEFT_SHIFT					ZEngine::Inputs::GlfwKey::KEY_LEFT_SHIFT
	#define ZENGINE_KEY_LEFT_CONTROL				ZEngine::Inputs::GlfwKey::KEY_LEFT_CONTROL
	#define ZENGINE_KEY_LEFT_ALT					ZEngine::Inputs::GlfwKey::KEY_LEFT_ALT
	#define ZENGINE_KEY_LEFT_SUPER					ZEngine::Inputs::GlfwKey::KEY_LEFT_SUPER
	#define ZENGINE_KEY_RIGHT_SHIFT					ZEngine::Inputs::GlfwKey::KEY_RIGHT_SHIFT
	#define ZENGINE_KEY_RIGHT_CONTROL				ZEngine::Inputs::GlfwKey::KEY_RIGHT_CONTROL
	#define ZENGINE_KEY_RIGHT_ALT					ZEngine::Inputs::GlfwKey::KEY_RIGHT_ALT
	#define ZENGINE_KEY_RIGHT_SUPER					ZEngine::Inputs::GlfwKey::KEY_RIGHT_SUPER
	#define ZENGINE_KEY_MENU						ZEngine::Inputs::GlfwKey::KEY_MENU
	#define ZENGINE_KEY_MOUSE_LEFT						ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_LEFT
	#define ZENGINE_KEY_MOUSE_RIGHT						ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_RIGHT
	#define ZENGINE_KEY_MOUSE_MIDDLE					ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_MIDDLE
	#define ZENGINE_MOUSE_BUTTON_4					ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_4
	#define ZENGINE_MOUSE_BUTTON_5					ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_5
	#define ZENGINE_MOUSE_BUTTON_6					ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_6
	#define ZENGINE_MOUSE_BUTTON_7					ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_7
	#define ZENGINE_MOUSE_BUTTON_8					ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_8

#endif // ZENGINE_KEY_MAPPING_SDL
