#pragma once
#include <ZEngineDef.h>

#define ZENGINE_KEY_UNKNOWN ZEngine::Inputs::GlfwKey::KEY_UNKNOWN
#define ZENGINE_KEY_SPACE ZEngine::Inputs::GlfwKey::KEY_SPACE
#define ZENGINE_KEY_APOSTROPHE ZEngine::Inputs::GlfwKey::KEY_APOSTROPHE
#define ZENGINE_KEY_COMMA ZEngine::Inputs::GlfwKey::KEY_COMMA
#define ZENGINE_KEY_MINUS ZEngine::Inputs::GlfwKey::KEY_MINUS
#define ZENGINE_KEY_PERIOD ZEngine::Inputs::GlfwKey::KEY_PERIOD
#define ZENGINE_KEY_SLASH ZEngine::Inputs::GlfwKey::KEY_SLASH
#define ZENGINE_KEY_0 ZEngine::Inputs::GlfwKey::KEY_0
#define ZENGINE_KEY_1 ZEngine::Inputs::GlfwKey::KEY_1
#define ZENGINE_KEY_2 ZEngine::Inputs::GlfwKey::KEY_2
#define ZENGINE_KEY_3 ZEngine::Inputs::GlfwKey::KEY_3
#define ZENGINE_KEY_4 ZEngine::Inputs::GlfwKey::KEY_4
#define ZENGINE_KEY_5 ZEngine::Inputs::GlfwKey::KEY_5
#define ZENGINE_KEY_6 ZEngine::Inputs::GlfwKey::KEY_6
#define ZENGINE_KEY_7 ZEngine::Inputs::GlfwKey::KEY_7
#define ZENGINE_KEY_8 ZEngine::Inputs::GlfwKey::KEY_8
#define ZENGINE_KEY_9 ZEngine::Inputs::GlfwKey::KEY_9
#define ZENGINE_KEY_SEMICOLON ZEngine::Inputs::GlfwKey::KEY_SEMICOLON
#define ZENGINE_KEY_EQUAL ZEngine::Inputs::GlfwKey::KEY_EQUAL
#define ZENGINE_KEY_A ZEngine::Inputs::GlfwKey::KEY_A
#define ZENGINE_KEY_B ZEngine::Inputs::GlfwKey::KEY_B
#define ZENGINE_KEY_C ZEngine::Inputs::GlfwKey::KEY_C
#define ZENGINE_KEY_D ZEngine::Inputs::GlfwKey::KEY_D
#define ZENGINE_KEY_E ZEngine::Inputs::GlfwKey::KEY_E
#define ZENGINE_KEY_F ZEngine::Inputs::GlfwKey::KEY_F
#define ZENGINE_KEY_G ZEngine::Inputs::GlfwKey::KEY_G
#define ZENGINE_KEY_H ZEngine::Inputs::GlfwKey::KEY_H
#define ZENGINE_KEY_I ZEngine::Inputs::GlfwKey::KEY_I
#define ZENGINE_KEY_J ZEngine::Inputs::GlfwKey::KEY_J
#define ZENGINE_KEY_K ZEngine::Inputs::GlfwKey::KEY_K
#define ZENGINE_KEY_L ZEngine::Inputs::GlfwKey::KEY_L
#define ZENGINE_KEY_M ZEngine::Inputs::GlfwKey::KEY_M
#define ZENGINE_KEY_N ZEngine::Inputs::GlfwKey::KEY_N
#define ZENGINE_KEY_O ZEngine::Inputs::GlfwKey::KEY_O
#define ZENGINE_KEY_P ZEngine::Inputs::GlfwKey::KEY_P
#define ZENGINE_KEY_Q ZEngine::Inputs::GlfwKey::KEY_Q
#define ZENGINE_KEY_R ZEngine::Inputs::GlfwKey::KEY_R
#define ZENGINE_KEY_S ZEngine::Inputs::GlfwKey::KEY_S
#define ZENGINE_KEY_T ZEngine::Inputs::GlfwKey::KEY_T
#define ZENGINE_KEY_U ZEngine::Inputs::GlfwKey::KEY_U
#define ZENGINE_KEY_V ZEngine::Inputs::GlfwKey::KEY_V
#define ZENGINE_KEY_W ZEngine::Inputs::GlfwKey::KEY_W
#define ZENGINE_KEY_X ZEngine::Inputs::GlfwKey::KEY_X
#define ZENGINE_KEY_Y ZEngine::Inputs::GlfwKey::KEY_Y
#define ZENGINE_KEY_Z ZEngine::Inputs::GlfwKey::KEY_Z
#define ZENGINE_KEY_LEFT_BRACKET ZEngine::Inputs::GlfwKey::KEY_LEFT_BRACKET
#define ZENGINE_KEY_BACKSLASH ZEngine::Inputs::GlfwKey::KEY_BACKSLASH
#define ZENGINE_KEY_RIGHT_BRACKET ZEngine::Inputs::GlfwKey::KEY_RIGHT_BRACKET
#define ZENGINE_KEY_GRAVE_ACCENT ZEngine::Inputs::GlfwKey::KEY_GRAVE_ACCENT
#define ZENGINE_KEY_WORLD_1 ZEngine::Inputs::GlfwKey::KEY_WORLD_1
#define ZENGINE_KEY_WORLD_2 ZEngine::Inputs::GlfwKey::KEY_WORLD_2
#define ZENGINE_KEY_ESCAPE ZEngine::Inputs::GlfwKey::KEY_ESCAPE
#define ZENGINE_KEY_ENTER ZEngine::Inputs::GlfwKey::KEY_ENTER
#define ZENGINE_KEY_TAB ZEngine::Inputs::GlfwKey::KEY_TAB
#define ZENGINE_KEY_BACKSPACE ZEngine::Inputs::GlfwKey::KEY_BACKSPACE
#define ZENGINE_KEY_INSERT ZEngine::Inputs::GlfwKey::KEY_INSERT
#define ZENGINE_KEY_DELETE ZEngine::Inputs::GlfwKey::KEY_DELETE
#define ZENGINE_KEY_RIGHT ZEngine::Inputs::GlfwKey::KEY_RIGHT
#define ZENGINE_KEY_LEFT ZEngine::Inputs::GlfwKey::KEY_LEFT
#define ZENGINE_KEY_DOWN ZEngine::Inputs::GlfwKey::KEY_DOWN
#define ZENGINE_KEY_UP ZEngine::Inputs::GlfwKey::KEY_UP
#define ZENGINE_KEY_PAGE_UP ZEngine::Inputs::GlfwKey::KEY_PAGE_UP
#define ZENGINE_KEY_PAGE_DOWN ZEngine::Inputs::GlfwKey::KEY_PAGE_DOWN
#define ZENGINE_KEY_HOME ZEngine::Inputs::GlfwKey::KEY_HOME
#define ZENGINE_KEY_END ZEngine::Inputs::GlfwKey::KEY_END
#define ZENGINE_KEY_CAPS_LOCK ZEngine::Inputs::GlfwKey::KEY_CAPS_LOCK
#define ZENGINE_KEY_SCROLL_LOCK ZEngine::Inputs::GlfwKey::KEY_SCROLL_LOCK
#define ZENGINE_KEY_NUM_LOCK ZEngine::Inputs::GlfwKey::KEY_NUM_LOCK
#define ZENGINE_KEY_PRINT_SCREEN ZEngine::Inputs::GlfwKey::KEY_PRINT_SCREEN
#define ZENGINE_KEY_PAUSE ZEngine::Inputs::GlfwKey::KEY_PAUSE
#define ZENGINE_KEY_F1 ZEngine::Inputs::GlfwKey::KEY_F1
#define ZENGINE_KEY_F2 ZEngine::Inputs::GlfwKey::KEY_F2
#define ZENGINE_KEY_F3 ZEngine::Inputs::GlfwKey::KEY_F3
#define ZENGINE_KEY_F4 ZEngine::Inputs::GlfwKey::KEY_F4
#define ZENGINE_KEY_F5 ZEngine::Inputs::GlfwKey::KEY_F5
#define ZENGINE_KEY_F6 ZEngine::Inputs::GlfwKey::KEY_F6
#define ZENGINE_KEY_F7 ZEngine::Inputs::GlfwKey::KEY_F7
#define ZENGINE_KEY_F8 ZEngine::Inputs::GlfwKey::KEY_F8
#define ZENGINE_KEY_F9 ZEngine::Inputs::GlfwKey::KEY_F9
#define ZENGINE_KEY_F10 ZEngine::Inputs::GlfwKey::KEY_F10
#define ZENGINE_KEY_F11 ZEngine::Inputs::GlfwKey::KEY_F11
#define ZENGINE_KEY_F12 ZEngine::Inputs::GlfwKey::KEY_F12
#define ZENGINE_KEY_F13 ZEngine::Inputs::GlfwKey::KEY_F13
#define ZENGINE_KEY_F14 ZEngine::Inputs::GlfwKey::KEY_F14
#define ZENGINE_KEY_F15 ZEngine::Inputs::GlfwKey::KEY_F15
#define ZENGINE_KEY_F16 ZEngine::Inputs::GlfwKey::KEY_F16
#define ZENGINE_KEY_F17 ZEngine::Inputs::GlfwKey::KEY_F17
#define ZENGINE_KEY_F18 ZEngine::Inputs::GlfwKey::KEY_F18
#define ZENGINE_KEY_F19 ZEngine::Inputs::GlfwKey::KEY_F19
#define ZENGINE_KEY_F20 ZEngine::Inputs::GlfwKey::KEY_F20
#define ZENGINE_KEY_F21 ZEngine::Inputs::GlfwKey::KEY_F21
#define ZENGINE_KEY_F22 ZEngine::Inputs::GlfwKey::KEY_F22
#define ZENGINE_KEY_F23 ZEngine::Inputs::GlfwKey::KEY_F23
#define ZENGINE_KEY_F24 ZEngine::Inputs::GlfwKey::KEY_F24
#define ZENGINE_KEY_F25 ZEngine::Inputs::GlfwKey::KEY_F25
#define ZENGINE_KEY_KP_0 ZEngine::Inputs::GlfwKey::KEY_KP_0
#define ZENGINE_KEY_KP_1 ZEngine::Inputs::GlfwKey::KEY_KP_1
#define ZENGINE_KEY_KP_2 ZEngine::Inputs::GlfwKey::KEY_KP_2
#define ZENGINE_KEY_KP_3 ZEngine::Inputs::GlfwKey::KEY_KP_3
#define ZENGINE_KEY_KP_4 ZEngine::Inputs::GlfwKey::KEY_KP_4
#define ZENGINE_KEY_KP_5 ZEngine::Inputs::GlfwKey::KEY_KP_5
#define ZENGINE_KEY_KP_6 ZEngine::Inputs::GlfwKey::KEY_KP_6
#define ZENGINE_KEY_KP_7 ZEngine::Inputs::GlfwKey::KEY_KP_7
#define ZENGINE_KEY_KP_8 ZEngine::Inputs::GlfwKey::KEY_KP_8
#define ZENGINE_KEY_KP_9 ZEngine::Inputs::GlfwKey::KEY_KP_9
#define ZENGINE_KEY_KP_DECIMAL ZEngine::Inputs::GlfwKey::KEY_KP_DECIMAL
#define ZENGINE_KEY_KP_DIVIDE ZEngine::Inputs::GlfwKey::KEY_KP_DIVIDE
#define ZENGINE_KEY_KP_MULTIPLY ZEngine::Inputs::GlfwKey::KEY_KP_MULTIPLY
#define ZENGINE_KEY_KP_SUBTRACT ZEngine::Inputs::GlfwKey::KEY_KP_SUBTRACT
#define ZENGINE_KEY_KP_ADD ZEngine::Inputs::GlfwKey::KEY_KP_ADD
#define ZENGINE_KEY_KP_ENTER ZEngine::Inputs::GlfwKey::KEY_KP_ENTER
#define ZENGINE_KEY_KP_EQUAL ZEngine::Inputs::GlfwKey::KEY_KP_EQUAL
#define ZENGINE_KEY_LEFT_SHIFT ZEngine::Inputs::GlfwKey::KEY_LEFT_SHIFT
#define ZENGINE_KEY_LEFT_CONTROL ZEngine::Inputs::GlfwKey::KEY_LEFT_CONTROL
#define ZENGINE_KEY_LEFT_ALT ZEngine::Inputs::GlfwKey::KEY_LEFT_ALT
#define ZENGINE_KEY_LEFT_SUPER ZEngine::Inputs::GlfwKey::KEY_LEFT_SUPER
#define ZENGINE_KEY_RIGHT_SHIFT ZEngine::Inputs::GlfwKey::KEY_RIGHT_SHIFT
#define ZENGINE_KEY_RIGHT_CONTROL ZEngine::Inputs::GlfwKey::KEY_RIGHT_CONTROL
#define ZENGINE_KEY_RIGHT_ALT ZEngine::Inputs::GlfwKey::KEY_RIGHT_ALT
#define ZENGINE_KEY_RIGHT_SUPER ZEngine::Inputs::GlfwKey::KEY_RIGHT_SUPER
#define ZENGINE_KEY_MENU ZEngine::Inputs::GlfwKey::KEY_MENU
#define ZENGINE_KEY_MOUSE_LEFT ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_LEFT
#define ZENGINE_KEY_MOUSE_RIGHT ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_RIGHT
#define ZENGINE_KEY_MOUSE_MIDDLE ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_MIDDLE
#define ZENGINE_MOUSE_BUTTON_4 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_4
#define ZENGINE_MOUSE_BUTTON_5 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_5
#define ZENGINE_MOUSE_BUTTON_6 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_6
#define ZENGINE_MOUSE_BUTTON_7 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_7
#define ZENGINE_MOUSE_BUTTON_8 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_8