#pragma once
#include <ZEngineDef.h>

#ifdef ZENGINE_KEY_MAPPING_SDL
#define ZENGINE_KEY_A ZEngine::Inputs::Key::A
#define ZENGINE_KEY_B ZEngine::Inputs::Key::B
#define ZENGINE_KEY_C ZEngine::Inputs::Key::C
#define ZENGINE_KEY_D ZEngine::Inputs::Key::D
#define ZENGINE_KEY_E ZEngine::Inputs::Key::E
#define ZENGINE_KEY_F ZEngine::Inputs::Key::F
#define ZENGINE_KEY_G ZEngine::Inputs::Key::G
#define ZENGINE_KEY_H ZEngine::Inputs::Key::H
#define ZENGINE_KEY_I ZEngine::Inputs::Key::I
#define ZENGINE_KEY_J ZEngine::Inputs::Key::J
#define ZENGINE_KEY_K ZEngine::Inputs::Key::K
#define ZENGINE_KEY_L ZEngine::Inputs::Key::L
#define ZENGINE_KEY_M ZEngine::Inputs::Key::M
#define ZENGINE_KEY_N ZEngine::Inputs::Key::N
#define ZENGINE_KEY_O ZEngine::Inputs::Key::O
#define ZENGINE_KEY_P ZEngine::Inputs::Key::P
#define ZENGINE_KEY_Q ZEngine::Inputs::Key::Q
#define ZENGINE_KEY_R ZEngine::Inputs::Key::R
#define ZENGINE_KEY_S ZEngine::Inputs::Key::S
#define ZENGINE_KEY_T ZEngine::Inputs::Key::T
#define ZENGINE_KEY_U ZEngine::Inputs::Key::U
#define ZENGINE_KEY_V ZEngine::Inputs::Key::V
#define ZENGINE_KEY_W ZEngine::Inputs::Key::W
#define ZENGINE_KEY_X ZEngine::Inputs::Key::X
#define ZENGINE_KEY_Y ZEngine::Inputs::Key::Y
#define ZENGINE_KEY_Z ZEngine::Inputs::Key::Z
#define ZENGINE_KEY_RETURN ZEngine::Inputs::Key::RETURN
#define ZENGINE_KEY_ESCAPE ZEngine::Inputs::Key::ESCAPE
#define ZENGINE_KEY_BACKSPACE ZEngine::Inputs::Key::BACKSPACE
#define ZENGINE_KEY_TAB ZEngine::Inputs::Key::TAB
#define ZENGINE_KEY_SPACE ZEngine::Inputs::Key::SPACE
#define ZENGINE_KEY_MINUS ZEngine::Inputs::Key::MINUS
#define ZENGINE_KEY_EQUALS ZEngine::Inputs::Key::EQUALS
#define ZENGINE_KEY_LEFTBRACKET ZEngine::Inputs::Key::LEFTBRACKET
#define ZENGINE_KEY_RIGHTBRACKET ZEngine::Inputs::Key::RIGHTBRACKET
#define ZENGINE_KEY_BACKSLASH ZEngine::Inputs::Key::BACKSLASH
#define ZENGINE_KEY_NONUSHASH ZEngine::Inputs::Key::NONUSHASH
#define ZENGINE_KEY_SEMICOLON ZEngine::Inputs::Key::SEMICOLON
#define ZENGINE_KEY_APOSTROPHE ZEngine::Inputs::Key::APOSTROPHE
#define ZENGINE_KEY_GRAVE ZEngine::Inputs::Key::GRAVE
#define ZENGINE_KEY_COMMA ZEngine::Inputs::Key::COMMA
#define ZENGINE_KEY_PERIOD ZEngine::Inputs::Key::PERIOD
#define ZENGINE_KEY_SLASH ZEngine::Inputs::Key::SLASH
#define ZENGINE_KEY_CAPSLOCK ZEngine::Inputs::Key::CAPSLOCK
#define ZENGINE_KEY_F1 ZEngine::Inputs::Key::F1
#define ZENGINE_KEY_F2 ZEngine::Inputs::Key::F2
#define ZENGINE_KEY_F3 ZEngine::Inputs::Key::F3
#define ZENGINE_KEY_F4 ZEngine::Inputs::Key::F4
#define ZENGINE_KEY_F5 ZEngine::Inputs::Key::F5
#define ZENGINE_KEY_F6 ZEngine::Inputs::Key::F6
#define ZENGINE_KEY_F7 ZEngine::Inputs::Key::F7
#define ZENGINE_KEY_F8 ZEngine::Inputs::Key::F8
#define ZENGINE_KEY_F9 ZEngine::Inputs::Key::F9
#define ZENGINE_KEY_F10 ZEngine::Inputs::Key::F10
#define ZENGINE_KEY_F11 ZEngine::Inputs::Key::F11
#define ZENGINE_KEY_F12 ZEngine::Inputs::Key::F12
#define ZENGINE_KEY_PRINTSCREEN ZEngine::Inputs::Key::PRINTSCREEN
#define ZENGINE_KEY_SCROLLLOCK ZEngine::Inputs::Key::SCROLLLOCK
#define ZENGINE_KEY_PAUSE ZEngine::Inputs::Key::PAUSE
#define ZENGINE_KEY_INSERT ZEngine::Inputs::Key::INSERT
#define ZENGINE_KEY_HOME ZEngine::Inputs::Key::HOME
#define ZENGINE_KEY_PAGEUP ZEngine::Inputs::Key::PAGEUP
#define ZENGINE_KEY_DELETE ZEngine::Inputs::Key::DELETE
#define ZENGINE_KEY_END ZEngine::Inputs::Key::END
#define ZENGINE_KEY_PAGEDOWN ZEngine::Inputs::Key::PAGEDOWN
#define ZENGINE_KEY_RIGHT ZEngine::Inputs::Key::RIGHT
#define ZENGINE_KEY_LEFT ZEngine::Inputs::Key::LEFT
#define ZENGINE_KEY_DOWN ZEngine::Inputs::Key::DOWN
#define ZENGINE_KEY_UP ZEngine::Inputs::Key::UP
#define ZENGINE_KEY_NUMLOCKCLEAR ZEngine::Inputs::Key::NUMLOCKCLEAR
#define ZENGINE_KEY_KP_DIVIDE ZEngine::Inputs::Key::KP_DIVIDE
#define ZENGINE_KEY_KP_MULTIPLY ZEngine::Inputs::Key::KP_MULTIPLY
#define ZENGINE_KEY_KP_MINUS ZEngine::Inputs::Key::KP_MINUS
#define ZENGINE_KEY_KP_PLUS ZEngine::Inputs::Key::KP_PLUS
#define ZENGINE_KEY_KP_ENTER ZEngine::Inputs::Key::KP_ENTER
#define ZENGINE_KEY_KP_1 ZEngine::Inputs::Key::KP_1
#define ZENGINE_KEY_KP_2 ZEngine::Inputs::Key::KP_2
#define ZENGINE_KEY_KP_3 ZEngine::Inputs::Key::KP_3
#define ZENGINE_KEY_KP_4 ZEngine::Inputs::Key::KP_4
#define ZENGINE_KEY_KP_5 ZEngine::Inputs::Key::KP_5
#define ZENGINE_KEY_KP_6 ZEngine::Inputs::Key::KP_6
#define ZENGINE_KEY_KP_7 ZEngine::Inputs::Key::KP_7
#define ZENGINE_KEY_KP_8 ZEngine::Inputs::Key::KP_8
#define ZENGINE_KEY_KP_9 ZEngine::Inputs::Key::KP_9
#define ZENGINE_KEY_KP_0 ZEngine::Inputs::Key::KP_0
#define ZENGINE_KEY_KP_PERIOD ZEngine::Inputs::Key::KP_PERIOD
#define ZENGINE_KEY_NONUSBACKSLASH ZEngine::Inputs::Key::NONUSBACKSLASH
#define ZENGINE_KEY_APPLICATION ZEngine::Inputs::Key::APPLICATION
#define ZENGINE_KEY_POWER ZEngine::Inputs::Key::POWER
#define ZENGINE_KEY_KP_EQUALS ZEngine::Inputs::Key::KP_EQUALS
#define ZENGINE_KEY_F13 ZEngine::Inputs::Key::F13
#define ZENGINE_KEY_F14 ZEngine::Inputs::Key::F14
#define ZENGINE_KEY_F15 ZEngine::Inputs::Key::F15
#define ZENGINE_KEY_F16 ZEngine::Inputs::Key::F16
#define ZENGINE_KEY_F17 ZEngine::Inputs::Key::F17
#define ZENGINE_KEY_F18 ZEngine::Inputs::Key::F18
#define ZENGINE_KEY_F19 ZEngine::Inputs::Key::F19
#define ZENGINE_KEY_F20 ZEngine::Inputs::Key::F20
#define ZENGINE_KEY_F21 ZEngine::Inputs::Key::F21
#define ZENGINE_KEY_F22 ZEngine::Inputs::Key::F22
#define ZENGINE_KEY_F23 ZEngine::Inputs::Key::F23
#define ZENGINE_KEY_F24 ZEngine::Inputs::Key::F24
#define ZENGINE_KEY_EXECUTE ZEngine::Inputs::Key::EXECUTE
#define ZENGINE_KEY_HELP ZEngine::Inputs::Key::HELP
#define ZENGINE_KEY_MENU ZEngine::Inputs::Key::MENU
#define ZENGINE_KEY_SELECT ZEngine::Inputs::Key::SELECT
#define ZENGINE_KEY_STOP ZEngine::Inputs::Key::STOP
#define ZENGINE_KEY_AGAIN ZEngine::Inputs::Key::AGAIN
#define ZENGINE_KEY_UNDO ZEngine::Inputs::Key::UNDO
#define ZENGINE_KEY_CUT ZEngine::Inputs::Key::CUT
#define ZENGINE_KEY_COPY ZEngine::Inputs::Key::COPY
#define ZENGINE_KEY_PASTE ZEngine::Inputs::Key::PASTE
#define ZENGINE_KEY_FIND ZEngine::Inputs::Key::FIND
#define ZENGINE_KEY_MUTE ZEngine::Inputs::Key::MUTE
#define ZENGINE_KEY_VOLUMEUP ZEngine::Inputs::Key::VOLUMEUP
#define ZENGINE_KEY_VOLUMEDOWN ZEngine::Inputs::Key::VOLUMEDOWN
#define ZENGINE_KEY_KP_COMMA ZEngine::Inputs::Key::KP_COMMA
#define ZENGINE_KEY_KP_EQUALSAS400 ZEngine::Inputs::Key::KP_EQUALSAS400
#define ZENGINE_KEY_INTERNATIONAL1 ZEngine::Inputs::Key::INTERNATIONAL1
#define ZENGINE_KEY_INTERNATIONAL2 ZEngine::Inputs::Key::INTERNATIONAL2
#define ZENGINE_KEY_INTERNATIONAL3 ZEngine::Inputs::Key::INTERNATIONAL3
#define ZENGINE_KEY_INTERNATIONAL4 ZEngine::Inputs::Key::INTERNATIONAL4
#define ZENGINE_KEY_INTERNATIONAL5 ZEngine::Inputs::Key::INTERNATIONAL5
#define ZENGINE_KEY_INTERNATIONAL6 ZEngine::Inputs::Key::INTERNATIONAL6
#define ZENGINE_KEY_INTERNATIONAL7 ZEngine::Inputs::Key::INTERNATIONAL7
#define ZENGINE_KEY_INTERNATIONAL8 ZEngine::Inputs::Key::INTERNATIONAL8
#define ZENGINE_KEY_INTERNATIONAL9 ZEngine::Inputs::Key::INTERNATIONAL9
#define ZENGINE_KEY_LANG1 ZEngine::Inputs::Key::LANG1
#define ZENGINE_KEY_LANG2 ZEngine::Inputs::Key::LANG2
#define ZENGINE_KEY_LANG3 ZEngine::Inputs::Key::LANG3
#define ZENGINE_KEY_LANG4 ZEngine::Inputs::Key::LANG4
#define ZENGINE_KEY_LANG5 ZEngine::Inputs::Key::LANG5
#define ZENGINE_KEY_LANG6 ZEngine::Inputs::Key::LANG6
#define ZENGINE_KEY_LANG7 ZEngine::Inputs::Key::LANG7
#define ZENGINE_KEY_LANG8 ZEngine::Inputs::Key::LANG8
#define ZENGINE_KEY_LANG9 ZEngine::Inputs::Key::LANG9
#define ZENGINE_KEY_ALTERASE ZEngine::Inputs::Key::ALTERASE
#define ZENGINE_KEY_SYSREQ ZEngine::Inputs::Key::SYSREQ
#define ZENGINE_KEY_CANCEL ZEngine::Inputs::Key::CANCEL
#define ZENGINE_KEY_CLEAR ZEngine::Inputs::Key::CLEAR
#define ZENGINE_KEY_PRIOR ZEngine::Inputs::Key::PRIOR
#define ZENGINE_KEY_RETURN2 ZEngine::Inputs::Key::RETURN2
#define ZENGINE_KEY_SEPARATOR ZEngine::Inputs::Key::SEPARATOR
#define ZENGINE_KEY_OUT ZEngine::Inputs::Key::OUT
#define ZENGINE_KEY_OPER ZEngine::Inputs::Key::OPER
#define ZENGINE_KEY_CLEARAGAIN ZEngine::Inputs::Key::CLEARAGAIN
#define ZENGINE_KEY_CRSEL ZEngine::Inputs::Key::CRSEL
#define ZENGINE_KEY_EXSEL ZEngine::Inputs::Key::EXSEL
#define ZENGINE_KEY_KP_00 ZEngine::Inputs::Key::KP_00
#define ZENGINE_KEY_KP_000 ZEngine::Inputs::Key::KP_000
#define ZENGINE_KEY_THOUSANDSSEPARATOR ZEngine::Inputs::Key::THOUSANDSSEPARATOR
#define ZENGINE_KEY_DECIMALSEPARATOR ZEngine::Inputs::Key::DECIMALSEPARATOR
#define ZENGINE_KEY_CURRENCYUNIT ZEngine::Inputs::Key::CURRENCYUNIT
#define ZENGINE_KEY_CURRENCYSUBUNIT ZEngine::Inputs::Key::CURRENCYSUBUNIT
#define ZENGINE_KEY_KP_LEFTPAREN ZEngine::Inputs::Key::KP_LEFTPAREN
#define ZENGINE_KEY_KP_RIGHTPAREN ZEngine::Inputs::Key::KP_RIGHTPAREN
#define ZENGINE_KEY_KP_LEFTBRACE ZEngine::Inputs::Key::KP_LEFTBRACE
#define ZENGINE_KEY_KP_RIGHTBRACE ZEngine::Inputs::Key::KP_RIGHTBRACE
#define ZENGINE_KEY_KP_TAB ZEngine::Inputs::Key::KP_TAB
#define ZENGINE_KEY_KP_BACKSPACE ZEngine::Inputs::Key::KP_BACKSPACE
#define ZENGINE_KEY_KP_A ZEngine::Inputs::Key::KP_A
#define ZENGINE_KEY_KP_B ZEngine::Inputs::Key::KP_B
#define ZENGINE_KEY_KP_C ZEngine::Inputs::Key::KP_C
#define ZENGINE_KEY_KP_D ZEngine::Inputs::Key::KP_D
#define ZENGINE_KEY_KP_E ZEngine::Inputs::Key::KP_E
#define ZENGINE_KEY_KP_F ZEngine::Inputs::Key::KP_F
#define ZENGINE_KEY_KP_XOR ZEngine::Inputs::Key::KP_XOR
#define ZENGINE_KEY_KP_POWER ZEngine::Inputs::Key::KP_POWER
#define ZENGINE_KEY_KP_PERCENT ZEngine::Inputs::Key::KP_PERCENT
#define ZENGINE_KEY_KP_LESS ZEngine::Inputs::Key::KP_LESS
#define ZENGINE_KEY_KP_GREATER ZEngine::Inputs::Key::KP_GREATER
#define ZENGINE_KEY_KP_AMPERSAND ZEngine::Inputs::Key::KP_AMPERSAND
#define ZENGINE_KEY_KP_DBLAMPERSAND ZEngine::Inputs::Key::KP_DBLAMPERSAND
#define ZENGINE_KEY_KP_VERTICALBAR ZEngine::Inputs::Key::KP_VERTICALBAR
#define ZENGINE_KEY_KP_DBLVERTICALBAR ZEngine::Inputs::Key::KP_DBLVERTICALBAR
#define ZENGINE_KEY_KP_COLON ZEngine::Inputs::Key::KP_COLON
#define ZENGINE_KEY_KP_HASH ZEngine::Inputs::Key::KP_HASH
#define ZENGINE_KEY_KP_SPACE ZEngine::Inputs::Key::KP_SPACE
#define ZENGINE_KEY_KP_AT ZEngine::Inputs::Key::KP_AT
#define ZENGINE_KEY_KP_EXCLAM ZEngine::Inputs::Key::KP_EXCLAM
#define ZENGINE_KEY_KP_MEMSTORE ZEngine::Inputs::Key::KP_MEMSTORE
#define ZENGINE_KEY_KP_MEMRECALL ZEngine::Inputs::Key::KP_MEMRECALL
#define ZENGINE_KEY_KP_MEMCLEAR ZEngine::Inputs::Key::KP_MEMCLEAR
#define ZENGINE_KEY_KP_MEMADD ZEngine::Inputs::Key::KP_MEMADD
#define ZENGINE_KEY_KP_MEMSUBTRACT ZEngine::Inputs::Key::KP_MEMSUBTRACT
#define ZENGINE_KEY_KP_MEMMULTIPLY ZEngine::Inputs::Key::KP_MEMMULTIPLY
#define ZENGINE_KEY_KP_MEMDIVIDE ZEngine::Inputs::Key::KP_MEMDIVIDE
#define ZENGINE_KEY_KP_PLUSMINUS ZEngine::Inputs::Key::KP_PLUSMINUS
#define ZENGINE_KEY_KP_CLEAR ZEngine::Inputs::Key::KP_CLEAR
#define ZENGINE_KEY_KP_CLEARENTRY ZEngine::Inputs::Key::KP_CLEARENTRY
#define ZENGINE_KEY_KP_BINARY ZEngine::Inputs::Key::KP_BINARY
#define ZENGINE_KEY_KP_OCTAL ZEngine::Inputs::Key::KP_OCTAL
#define ZENGINE_KEY_KP_DECIMAL ZEngine::Inputs::Key::KP_DECIMAL
#define ZENGINE_KEY_KP_HEXADECIMAL ZEngine::Inputs::Key::KP_HEXADECIMAL
#define ZENGINE_KEY_LCTRL ZEngine::Inputs::Key::LCTRL
#define ZENGINE_KEY_LSHIFT ZEngine::Inputs::Key::LSHIFT
#define ZENGINE_KEY_LALT ZEngine::Inputs::Key::LALT
#define ZENGINE_KEY_LGUI ZEngine::Inputs::Key::LGUI
#define ZENGINE_KEY_RCTRL ZEngine::Inputs::Key::RCTRL
#define ZENGINE_KEY_RSHIFT ZEngine::Inputs::Key::RSHIFT
#define ZENGINE_KEY_RALT ZEngine::Inputs::Key::RALT
#define ZENGINE_KEY_RGUI ZEngine::Inputs::Key::RGUI
#define ZENGINE_KEY_MODE ZEngine::Inputs::Key::MODE
#define ZENGINE_KEY_AUDIONEXT ZEngine::Inputs::Key::AUDIONEXT
#define ZENGINE_KEY_AUDIOPREV ZEngine::Inputs::Key::AUDIOPREV
#define ZENGINE_KEY_AUDIOSTOP ZEngine::Inputs::Key::AUDIOSTOP
#define ZENGINE_KEY_AUDIOPLAY ZEngine::Inputs::Key::AUDIOPLAY
#define ZENGINE_KEY_AUDIOMUTE ZEngine::Inputs::Key::AUDIOMUTE
#define ZENGINE_KEY_MEDIASELECT ZEngine::Inputs::Key::MEDIASELECT
#define ZENGINE_KEY_WWW ZEngine::Inputs::Key::WWW
#define ZENGINE_KEY_MAIL ZEngine::Inputs::Key::MAIL
#define ZENGINE_KEY_CALCULATOR ZEngine::Inputs::Key::CALCULATOR
#define ZENGINE_KEY_COMPUTER ZEngine::Inputs::Key::COMPUTER
#define ZENGINE_KEY_AC_SEARCH ZEngine::Inputs::Key::AC_SEARCH
#define ZENGINE_KEY_AC_HOME ZEngine::Inputs::Key::AC_HOME
#define ZENGINE_KEY_AC_BACK ZEngine::Inputs::Key::AC_BACK
#define ZENGINE_KEY_AC_FORWARD ZEngine::Inputs::Key::AC_FORWARD
#define ZENGINE_KEY_AC_STOP ZEngine::Inputs::Key::AC_STOP
#define ZENGINE_KEY_AC_REFRESH ZEngine::Inputs::Key::AC_REFRESH
#define ZENGINE_KEY_AC_BOOKMARKS ZEngine::Inputs::Key::AC_BOOKMARKS
#define ZENGINE_KEY_BRIGHTNESSDOWN ZEngine::Inputs::Key::BRIGHTNESSDOWN
#define ZENGINE_KEY_BRIGHTNESSUP ZEngine::Inputs::Key::BRIGHTNESSUP
#define ZENGINE_KEY_DISPLAYSWITCH ZEngine::Inputs::Key::DISPLAYSWITCH
#define ZENGINE_KEY_KBDILLUMTOGGLE ZEngine::Inputs::Key::KBDILLUMTOGGLE
#define ZENGINE_KEY_KBDILLUMDOWN ZEngine::Inputs::Key::KBDILLUMDOWN
#define ZENGINE_KEY_KBDILLUMUP ZEngine::Inputs::Key::KBDILLUMUP
#define ZENGINE_KEY_EJECT ZEngine::Inputs::Key::EJECT
#define ZENGINE_KEY_SLEEP ZEngine::Inputs::Key::SLEEP
#define ZENGINE_KEY_APP1 ZEngine::Inputs::Key::APP1
#define ZENGINE_KEY_APP2 ZEngine::Inputs::Key::APP2

#define ZENGINE_KEY_MOUSE_LEFT ZEngine::Inputs::Key::MOUSE_LEFT
#define ZENGINE_KEY_MOUSE_RIGHT ZEngine::Inputs::Key::MOUSE_RIGHT
#define ZENGINE_KEY_MOUSE_WHEEL ZEngine::Inputs::Key::MOUSE_WHEEL

#else

#define ZENGINE_KEY_UNKNOWN ZEngine::Inputs::GlfwKey::KEY_UNKNOWN
#define ZENGINE_KEY_SPACE ZEngine::Inputs::GlfwKey::KEY_SPACE
#define ZENGINE_KEY_APOSTROPHE ZEngine::Inputs::GlfwKey::KEY_APOSTROPHE
#define ZENGINE_KEY_COMMA ZEngine::Inputs::GlfwKey::KEY_COMMA
#define ZENGINE_KEY_MINUS ZEngine::Inputs::GlfwKey::KEY_MINUS
#define ZENGINE_KEY_PERIOD ZEngine::Inputs::GlfwKey::KEY_PERIOD
#define ZENGINE_KEY_SLASH ZEngine::Inputs::GlfwKey::KEY_SLASH
#define ZENGINE_KEY_0 ZEngine::Inputs::GlfwKey::KEY_0
#define ZENGINE_KEY_1 ZEngine::Inputs::GlfwKey::KEY_1
#define ZENGINE_KEY_2 ZEngine::Inputs::GlfwKey::KEY_2
#define ZENGINE_KEY_3 ZEngine::Inputs::GlfwKey::KEY_3
#define ZENGINE_KEY_4 ZEngine::Inputs::GlfwKey::KEY_4
#define ZENGINE_KEY_5 ZEngine::Inputs::GlfwKey::KEY_5
#define ZENGINE_KEY_6 ZEngine::Inputs::GlfwKey::KEY_6
#define ZENGINE_KEY_7 ZEngine::Inputs::GlfwKey::KEY_7
#define ZENGINE_KEY_8 ZEngine::Inputs::GlfwKey::KEY_8
#define ZENGINE_KEY_9 ZEngine::Inputs::GlfwKey::KEY_9
#define ZENGINE_KEY_SEMICOLON ZEngine::Inputs::GlfwKey::KEY_SEMICOLON
#define ZENGINE_KEY_EQUAL ZEngine::Inputs::GlfwKey::KEY_EQUAL
#define ZENGINE_KEY_A ZEngine::Inputs::GlfwKey::KEY_A
#define ZENGINE_KEY_B ZEngine::Inputs::GlfwKey::KEY_B
#define ZENGINE_KEY_C ZEngine::Inputs::GlfwKey::KEY_C
#define ZENGINE_KEY_D ZEngine::Inputs::GlfwKey::KEY_D
#define ZENGINE_KEY_E ZEngine::Inputs::GlfwKey::KEY_E
#define ZENGINE_KEY_F ZEngine::Inputs::GlfwKey::KEY_F
#define ZENGINE_KEY_G ZEngine::Inputs::GlfwKey::KEY_G
#define ZENGINE_KEY_H ZEngine::Inputs::GlfwKey::KEY_H
#define ZENGINE_KEY_I ZEngine::Inputs::GlfwKey::KEY_I
#define ZENGINE_KEY_J ZEngine::Inputs::GlfwKey::KEY_J
#define ZENGINE_KEY_K ZEngine::Inputs::GlfwKey::KEY_K
#define ZENGINE_KEY_L ZEngine::Inputs::GlfwKey::KEY_L
#define ZENGINE_KEY_M ZEngine::Inputs::GlfwKey::KEY_M
#define ZENGINE_KEY_N ZEngine::Inputs::GlfwKey::KEY_N
#define ZENGINE_KEY_O ZEngine::Inputs::GlfwKey::KEY_O
#define ZENGINE_KEY_P ZEngine::Inputs::GlfwKey::KEY_P
#define ZENGINE_KEY_Q ZEngine::Inputs::GlfwKey::KEY_Q
#define ZENGINE_KEY_R ZEngine::Inputs::GlfwKey::KEY_R
#define ZENGINE_KEY_S ZEngine::Inputs::GlfwKey::KEY_S
#define ZENGINE_KEY_T ZEngine::Inputs::GlfwKey::KEY_T
#define ZENGINE_KEY_U ZEngine::Inputs::GlfwKey::KEY_U
#define ZENGINE_KEY_V ZEngine::Inputs::GlfwKey::KEY_V
#define ZENGINE_KEY_W ZEngine::Inputs::GlfwKey::KEY_W
#define ZENGINE_KEY_X ZEngine::Inputs::GlfwKey::KEY_X
#define ZENGINE_KEY_Y ZEngine::Inputs::GlfwKey::KEY_Y
#define ZENGINE_KEY_Z ZEngine::Inputs::GlfwKey::KEY_Z
#define ZENGINE_KEY_LEFT_BRACKET ZEngine::Inputs::GlfwKey::KEY_LEFT_BRACKET
#define ZENGINE_KEY_BACKSLASH ZEngine::Inputs::GlfwKey::KEY_BACKSLASH
#define ZENGINE_KEY_RIGHT_BRACKET ZEngine::Inputs::GlfwKey::KEY_RIGHT_BRACKET
#define ZENGINE_KEY_GRAVE_ACCENT ZEngine::Inputs::GlfwKey::KEY_GRAVE_ACCENT
#define ZENGINE_KEY_WORLD_1 ZEngine::Inputs::GlfwKey::KEY_WORLD_1
#define ZENGINE_KEY_WORLD_2 ZEngine::Inputs::GlfwKey::KEY_WORLD_2
#define ZENGINE_KEY_ESCAPE ZEngine::Inputs::GlfwKey::KEY_ESCAPE
#define ZENGINE_KEY_ENTER ZEngine::Inputs::GlfwKey::KEY_ENTER
#define ZENGINE_KEY_TAB ZEngine::Inputs::GlfwKey::KEY_TAB
#define ZENGINE_KEY_BACKSPACE ZEngine::Inputs::GlfwKey::KEY_BACKSPACE
#define ZENGINE_KEY_INSERT ZEngine::Inputs::GlfwKey::KEY_INSERT
#define ZENGINE_KEY_DELETE ZEngine::Inputs::GlfwKey::KEY_DELETE
#define ZENGINE_KEY_RIGHT ZEngine::Inputs::GlfwKey::KEY_RIGHT
#define ZENGINE_KEY_LEFT ZEngine::Inputs::GlfwKey::KEY_LEFT
#define ZENGINE_KEY_DOWN ZEngine::Inputs::GlfwKey::KEY_DOWN
#define ZENGINE_KEY_UP ZEngine::Inputs::GlfwKey::KEY_UP
#define ZENGINE_KEY_PAGE_UP ZEngine::Inputs::GlfwKey::KEY_PAGE_UP
#define ZENGINE_KEY_PAGE_DOWN ZEngine::Inputs::GlfwKey::KEY_PAGE_DOWN
#define ZENGINE_KEY_HOME ZEngine::Inputs::GlfwKey::KEY_HOME
#define ZENGINE_KEY_END ZEngine::Inputs::GlfwKey::KEY_END
#define ZENGINE_KEY_CAPS_LOCK ZEngine::Inputs::GlfwKey::KEY_CAPS_LOCK
#define ZENGINE_KEY_SCROLL_LOCK ZEngine::Inputs::GlfwKey::KEY_SCROLL_LOCK
#define ZENGINE_KEY_NUM_LOCK ZEngine::Inputs::GlfwKey::KEY_NUM_LOCK
#define ZENGINE_KEY_PRINT_SCREEN ZEngine::Inputs::GlfwKey::KEY_PRINT_SCREEN
#define ZENGINE_KEY_PAUSE ZEngine::Inputs::GlfwKey::KEY_PAUSE
#define ZENGINE_KEY_F1 ZEngine::Inputs::GlfwKey::KEY_F1
#define ZENGINE_KEY_F2 ZEngine::Inputs::GlfwKey::KEY_F2
#define ZENGINE_KEY_F3 ZEngine::Inputs::GlfwKey::KEY_F3
#define ZENGINE_KEY_F4 ZEngine::Inputs::GlfwKey::KEY_F4
#define ZENGINE_KEY_F5 ZEngine::Inputs::GlfwKey::KEY_F5
#define ZENGINE_KEY_F6 ZEngine::Inputs::GlfwKey::KEY_F6
#define ZENGINE_KEY_F7 ZEngine::Inputs::GlfwKey::KEY_F7
#define ZENGINE_KEY_F8 ZEngine::Inputs::GlfwKey::KEY_F8
#define ZENGINE_KEY_F9 ZEngine::Inputs::GlfwKey::KEY_F9
#define ZENGINE_KEY_F10 ZEngine::Inputs::GlfwKey::KEY_F10
#define ZENGINE_KEY_F11 ZEngine::Inputs::GlfwKey::KEY_F11
#define ZENGINE_KEY_F12 ZEngine::Inputs::GlfwKey::KEY_F12
#define ZENGINE_KEY_F13 ZEngine::Inputs::GlfwKey::KEY_F13
#define ZENGINE_KEY_F14 ZEngine::Inputs::GlfwKey::KEY_F14
#define ZENGINE_KEY_F15 ZEngine::Inputs::GlfwKey::KEY_F15
#define ZENGINE_KEY_F16 ZEngine::Inputs::GlfwKey::KEY_F16
#define ZENGINE_KEY_F17 ZEngine::Inputs::GlfwKey::KEY_F17
#define ZENGINE_KEY_F18 ZEngine::Inputs::GlfwKey::KEY_F18
#define ZENGINE_KEY_F19 ZEngine::Inputs::GlfwKey::KEY_F19
#define ZENGINE_KEY_F20 ZEngine::Inputs::GlfwKey::KEY_F20
#define ZENGINE_KEY_F21 ZEngine::Inputs::GlfwKey::KEY_F21
#define ZENGINE_KEY_F22 ZEngine::Inputs::GlfwKey::KEY_F22
#define ZENGINE_KEY_F23 ZEngine::Inputs::GlfwKey::KEY_F23
#define ZENGINE_KEY_F24 ZEngine::Inputs::GlfwKey::KEY_F24
#define ZENGINE_KEY_F25 ZEngine::Inputs::GlfwKey::KEY_F25
#define ZENGINE_KEY_KP_0 ZEngine::Inputs::GlfwKey::KEY_KP_0
#define ZENGINE_KEY_KP_1 ZEngine::Inputs::GlfwKey::KEY_KP_1
#define ZENGINE_KEY_KP_2 ZEngine::Inputs::GlfwKey::KEY_KP_2
#define ZENGINE_KEY_KP_3 ZEngine::Inputs::GlfwKey::KEY_KP_3
#define ZENGINE_KEY_KP_4 ZEngine::Inputs::GlfwKey::KEY_KP_4
#define ZENGINE_KEY_KP_5 ZEngine::Inputs::GlfwKey::KEY_KP_5
#define ZENGINE_KEY_KP_6 ZEngine::Inputs::GlfwKey::KEY_KP_6
#define ZENGINE_KEY_KP_7 ZEngine::Inputs::GlfwKey::KEY_KP_7
#define ZENGINE_KEY_KP_8 ZEngine::Inputs::GlfwKey::KEY_KP_8
#define ZENGINE_KEY_KP_9 ZEngine::Inputs::GlfwKey::KEY_KP_9
#define ZENGINE_KEY_KP_DECIMAL ZEngine::Inputs::GlfwKey::KEY_KP_DECIMAL
#define ZENGINE_KEY_KP_DIVIDE ZEngine::Inputs::GlfwKey::KEY_KP_DIVIDE
#define ZENGINE_KEY_KP_MULTIPLY ZEngine::Inputs::GlfwKey::KEY_KP_MULTIPLY
#define ZENGINE_KEY_KP_SUBTRACT ZEngine::Inputs::GlfwKey::KEY_KP_SUBTRACT
#define ZENGINE_KEY_KP_ADD ZEngine::Inputs::GlfwKey::KEY_KP_ADD
#define ZENGINE_KEY_KP_ENTER ZEngine::Inputs::GlfwKey::KEY_KP_ENTER
#define ZENGINE_KEY_KP_EQUAL ZEngine::Inputs::GlfwKey::KEY_KP_EQUAL
#define ZENGINE_KEY_LEFT_SHIFT ZEngine::Inputs::GlfwKey::KEY_LEFT_SHIFT
#define ZENGINE_KEY_LEFT_CONTROL ZEngine::Inputs::GlfwKey::KEY_LEFT_CONTROL
#define ZENGINE_KEY_LEFT_ALT ZEngine::Inputs::GlfwKey::KEY_LEFT_ALT
#define ZENGINE_KEY_LEFT_SUPER ZEngine::Inputs::GlfwKey::KEY_LEFT_SUPER
#define ZENGINE_KEY_RIGHT_SHIFT ZEngine::Inputs::GlfwKey::KEY_RIGHT_SHIFT
#define ZENGINE_KEY_RIGHT_CONTROL ZEngine::Inputs::GlfwKey::KEY_RIGHT_CONTROL
#define ZENGINE_KEY_RIGHT_ALT ZEngine::Inputs::GlfwKey::KEY_RIGHT_ALT
#define ZENGINE_KEY_RIGHT_SUPER ZEngine::Inputs::GlfwKey::KEY_RIGHT_SUPER
#define ZENGINE_KEY_MENU ZEngine::Inputs::GlfwKey::KEY_MENU
#define ZENGINE_KEY_MOUSE_LEFT ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_LEFT
#define ZENGINE_KEY_MOUSE_RIGHT ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_RIGHT
#define ZENGINE_KEY_MOUSE_MIDDLE ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_MIDDLE
#define ZENGINE_MOUSE_BUTTON_4 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_4
#define ZENGINE_MOUSE_BUTTON_5 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_5
#define ZENGINE_MOUSE_BUTTON_6 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_6
#define ZENGINE_MOUSE_BUTTON_7 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_7
#define ZENGINE_MOUSE_BUTTON_8 ZEngine::Inputs::GlfwKey::MOUSE_BUTTON_8

#endif
