on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yml@v1

  macOS:
    uses: ./.github/workflows/macOS-build.yml@v1

  # linux:
  #   uses: ./.github/workflows/linux-build.yml