on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  clang-format:
    strategy:
      matrix:
        directories: ['${{github.workspace }}/RendererEngine/ZEngine', '${{github.workspace }}/RendererEngine/Tetragrama']
    uses: ./.github/workflows/job-clangformat.yml
    with:
      srcDirectory: ${{ matrix.directories }}

  windows:
    needs: clang-format
    uses: ./.github/workflows/windows-build.yml

  macOS:
    needs: clang-format
    uses: ./.github/workflows/macOS-build.yml

  # linux:
  #   uses: ./.github/workflows/linux-build.yml