on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yml

  macOS:
    uses: ./.github/workflows/macOS-build.yml

  linux:
    uses: ./.github/workflows/linux-build.yml