# CMake build of ZEngine for Windows
#
name: Windows Build Workflow

permissions:
  packages: write

on:
  workflow_call:
    inputs:
      targetFramework:
        type: string
        required: true
      configuration:
        type: string
        default: 'Debug'

jobs:
  cmake-build:
    name: cmake-build-windows-${{ inputs.configuration }}
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: C:\Program Files\LLVM
          key: llvm-20.1.7-windows

      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        run: choco install llvm --version=20.1.7 --no-progress -y

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Cache CMake dependencies
        uses: actions/cache@v4
        with:
          path: Result.Windows.x64.MultiConfig/_deps
          key: cmake-deps-windows-ninja-${{ hashFiles('dependencies.cmake') }}
          restore-keys: cmake-deps-windows-ninja-

      - name: CMake Build
        run: .\Scripts\BuildEngine.ps1 -Configurations ${{inputs.configuration}} -Generator Ninja -RunClangFormat 0
        shell: pwsh

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: Build-Windows-x64-${{inputs.configuration}}
          if-no-files-found: error
          path: |
            Result.Windows.x64.MultiConfig/bin/
            Result.Windows.x64.MultiConfig/lib/*vulkan*
            Result.Windows.x64.MultiConfig/tests/ZEngineTests.exe
