# Run tests for Windows
#
name: Windows Test Workflow

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        default: 'Debug'

jobs:
  test:
    name: test-windows-${{ inputs.configuration }}
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: Result.Windows.x64.MultiConfig
          name: Build-Windows-x64-${{ inputs.configuration }}

      - name: Download Vulkan Artifacts
        uses: actions/download-artifact@v4
        with:
          path: vulkan-build
          name: Vulkan-build-x64-release

      - name: Run Tests
        shell: pwsh
        run: |
          $env:PATH = ".\vulkan-build\;$env:PATH"
          .\Scripts\RunTests.ps1 -Configurations ${{ inputs.configuration }}
