# Deploy for macOS
#
name: macOS Deploy Workflow

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        default: 'Release'
      architecture:
        type: string
        default: 'x64'

jobs:
  deploy:
    name: deploy-macOS-${{ inputs.architecture }}-${{ inputs.configuration }}
    runs-on: ${{ matrix.architecture == 'x64' && 'macos-13' || 'macos-latest' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: Result.Darwin.x64.${{ inputs.configuration }}
          name: Build-macOS-${{ inputs.architecture }}-Release

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS-${{ inputs.architecture }}-${{ inputs.configuration }}
          path: Result.Darwin.x64.${{ inputs.configuration }}/Panzerfaust/${{ inputs.configuration }}/net6.0/osx-${{ inputs.architecture }}/publish/
