name: Code Formatting Check

on:
    workflow_call:

jobs:
    format:
        name: clang-format
        runs-on: windows-2022
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install LLVM if not present
              shell: pwsh
              run: |
                  if (-not (Get-Command clang-format -ErrorAction SilentlyContinue)) {
                    choco install llvm --no-progress -y
                  } else {
                    Write-Host "LLVM already available: $(clang-format --version)"
                  }

            - name: Checking formatting
              run: |
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/ZEngine -RunAsCheck
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/Tetragrama -RunAsCheck
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/Obelisk -RunAsCheck
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/Resources/Shaders -RunAsCheck
              shell: pwsh
