name: Code Formatting Check

on:
    workflow_call:

jobs:
    format:
        name: clang-format
        runs-on: windows-2022
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Cache LLVM
              id: cache-llvm
              uses: actions/cache@v4
              with:
                  path: C:\Program Files\LLVM
                  key: llvm-20.1.7-windows

            - name: Install LLVM
              if: steps.cache-llvm.outputs.cache-hit != 'true'
              run: choco install llvm --version=20.1.7 --no-progress -y

            - name: Checking formatting
              run: |
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/ZEngine -RunAsCheck
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/Tetragrama -RunAsCheck
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/Obelisk -RunAsCheck
                .\Scripts\ClangFormat.ps1 -SourceDirectory ${{ github.workspace }}/Resources/Shaders -RunAsCheck
              shell: pwsh
