# Deploy for linux
#
name: linux Deploy Workflow

on:
  workflow_call:
    inputs:
      targetFramework:
        type: string
        required: true
      configuration:
        type: string
        default: 'Release'

jobs:
  deploy:
    name: deploy-linux-${{ inputs.configuration }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: Result.Linux.x64.${{ inputs.configuration }}
          name: Build-linux-Release

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ inputs.configuration }}
          path: Result.Linux.x64.${{inputs.configuration}}/Panzerfaust/${{ inputs.configuration }}/${{inputs.targetFramework}}/publish/
