name: ZEngine Linux Build

on:
  workflow_call:
    inputs:
      targetFramework:
        required: true
        type: string

jobs:
  cmake-build:
    strategy:
      matrix:
        buildConfiguration: [Debug, Release]
    uses: ./.github/workflows/job-cmakebuild-linux.yml
    with:
      configuration: ${{matrix.buildConfiguration}}
      targetframework: ${{inputs.targetFramework}}

  test:
    needs: cmake-build
    strategy:
      matrix:
        testConfiguration: [Debug, Release]
    uses: ./.github/workflows/job-test-linux.yml
    with:
      configuration: ${{matrix.testConfiguration}}

  deploy:
    needs: test
    uses: ./.github/workflows/job-deploy-linux.yml
    with:
      configuration: Release
      targetframework: ${{inputs.targetFramework}}

