name: ZEngine macOS Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  macOS-Build:
    runs-on: macos-13
    strategy:
      matrix:
          buildConfiguration: [Debug, Release]

    steps:      
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: CMake Build
      run: .\Scripts\BuildEngine.ps1 -Configurations ${{matrix.buildConfiguration}}
      shell: pwsh
