name: ZEngine macOS Build

on:
  workflow_call:
    inputs:
      targetFramework:
        type: string
        required: true
      run_debug:
        type: boolean
        default: true
      run_release:
        type: boolean
        default: false
      run_deploy:
        type: boolean
        default: false

jobs:
  cmake-build-debug:
    if: ${{ inputs.run_debug }}
    uses: ./.github/workflows/job-cmakebuild-macOS.yml
    with:
      configuration: Debug
      architecture: arm64
      targetFramework: ${{ inputs.targetFramework }}

  cmake-build-release:
    if: ${{ inputs.run_release || inputs.run_deploy }}
    uses: ./.github/workflows/job-cmakebuild-macOS.yml
    with:
      configuration: Release
      architecture: arm64
      targetFramework: ${{ inputs.targetFramework }}

  test-debug:
    needs: cmake-build-debug
    if: ${{ inputs.run_debug }}
    uses: ./.github/workflows/job-test-macOS.yml
    with:
      configuration: Debug
      architecture: arm64

  test-release:
    needs: cmake-build-release
    if: ${{ inputs.run_release || inputs.run_deploy }}
    uses: ./.github/workflows/job-test-macOS.yml
    with:
      configuration: Release
      architecture: arm64

  deploy:
    needs: test-release
    if: ${{ inputs.run_deploy }}
    uses: ./.github/workflows/job-deploy-macOS.yml
    with:
      configuration: Release
      architecture: arm64
      targetFramework: ${{ inputs.targetFramework }}
