name: ZEngine macOS Build

on: workflow_call

jobs:
  cmake-build:
    strategy:
      matrix:
        buildConfiguration: [Debug, Release]
        architecture: [x64, arm64]
    uses: ./.github/workflows/job-cmakebuild-macOS-${{ matrix.architecture }}.yml
    with:
      configuration: ${{matrix.buildConfiguration}}

  test:
    needs: cmake-build
    strategy:
      matrix:
        testConfiguration: [Debug, Release]
        architecture: [x64, arm64]
    uses: ./.github/workflows/job-test-macOS-${{ matrix.architecture }}.yml
    with:
      configuration: ${{matrix.testConfiguration}}

  deploy:
    needs: test
    strategy:
      matrix:
        architecture: [x64, arm64]
    uses: ./.github/workflows/job-deploy-macOS.yml
    with:
      configuration: Release
      architecture: ${{ matrix.architecture }}
