name: ZEngine Window Build

on:
  workflow_call:
    inputs:
      version_file:
        type: string
        default: '1'
jobs:
  cmake-build:
    strategy:
      matrix:
        buildConfiguration: [Debug, Release]
    uses: ./.github/workflows/job-cmakebuild-windows.yml
    with:
      configuration: ${{matrix.buildConfiguration}}

  test:
    needs: cmake-build
    strategy:
      matrix:
        testConfiguration: [Debug, Release]
    uses: ./.github/workflows/job-test-windows.yml
    with:
      configuration: ${{matrix.testConfiguration}}

  deploy:
    needs: test
    uses: ./.github/workflows/job-deploy-windows.yml